-- TAULA RSC_CATDOC
CREATE TABLE RSC_CATDOC (
  CDC_CODI    NUMBER(19) NOT NULL,
  CDC_ORDEN   NUMBER(10),
  CDC_ADMRSP  NUMBER(2),
  CDC_CODEXD  NUMBER(19)
);
ALTER TABLE RSC_CATDOC ADD (CONSTRAINT RSC_CATDOC_PK PRIMARY KEY  (CDC_CODI));

-- TAULA RSC_TRACDC
CREATE TABLE RSC_TRACDC (
  TCD_CODCDC  NUMBER(19) NOT NULL,
  TCD_DESCRI  VARCHAR2(4000 CHAR),
  TCD_CODIDI  VARCHAR2(2 CHAR),
  TCD_NOM     VARCHAR2(256 CHAR)
);
ALTER TABLE RSC_TRACDC ADD (CONSTRAINT RSC_TRACDC_PK PRIMARY KEY (TCD_CODCDC, TCD_CODIDI));
ALTER TABLE RSC_TRACDC ADD (CONSTRAINT RSC_TCDCDC_FK FOREIGN KEY (TCD_CODCDC) REFERENCES RSC_CATDOC (CDC_CODI));

-- TAULA RSC_EXCDOC
CREATE TABLE RSC_EXCDOC (
  EXD_CODI  NUMBER(19) NOT NULL
);
ALTER TABLE RSC_EXCDOC ADD (CONSTRAINT RSC_EXCDOC_PK PRIMARY KEY (EXD_CODI));
ALTER TABLE RSC_CATDOC ADD (CONSTRAINT RSC_CDCEXD_FK FOREIGN KEY (CDC_CODEXD) REFERENCES RSC_EXCDOC (EXD_CODI));

-- TAULA RSC_TRAEXD
CREATE TABLE RSC_TRAEXD (
  TED_CODEXD  NUMBER(19) NOT NULL,
  TED_NOM     VARCHAR2(256 CHAR),
  TED_DESCRI  VARCHAR2(4000 CHAR),
  TED_CODIDI  VARCHAR2(2 CHAR)
);
ALTER TABLE RSC_TRAEXD ADD (CONSTRAINT RSC_TRAEXD_PK PRIMARY KEY (TED_CODEXD, TED_CODIDI));
ALTER TABLE RSC_TRAEXD ADD (CONSTRAINT RSC_TEDEXD_FK FOREIGN KEY (TED_CODEXD) REFERENCES RSC_EXCDOC (EXD_CODI));

-- TAULA RSC_DOCTRA
ALTER TABLE RSC_DOCTRA ADD (
  DOC_CODCDC  NUMBER(19),
  DOC_CODEXD  NUMBER(19)
);
ALTER TABLE RSC_DOCTRA ADD CONSTRAINT RSC_DOCTRA_CATDOC_FK FOREIGN KEY (DOC_CODCDC) REFERENCES RSC_CATDOC (CDC_CODI);
ALTER TABLE RSC_DOCTRA ADD CONSTRAINT RSC_DOCTRA_EXCDOC_FK FOREIGN KEY (DOC_CODEXD) REFERENCES RSC_EXCDOC (EXD_CODI);

-- TAULA RSC_TRAMIT
ALTER TABLE RSC_TRAMIT ADD (TRA_DATINICI date);
ALTER TABLE RSC_TRAMIT ADD (TRA_DATTANCAMENT date);

-- TAULA RSC_UNIADM ISSUE #343
ALTER TABLE RSC_UNIADM ADD UNA_EMAILR varchar2(256 CHAR);

-- TAULA RSC_PROCED ISSUE #351
ALTER TABLE RSC_PROCED ADD PRO_CODUNA_SERV number(19,0);