-- TAULA RSC_POBFIC
CREATE TABLE RSC_POBFIC(
  PFC_CODFIC  NUMBER(19) NOT NULL,
  PFC_CODPOB  NUMBER(19) NOT NULL
);
ALTER TABLE RSC_POBFIC ADD ( 
 CONSTRAINT RSC_POBFIC_PK  PRIMARY KEY (PFC_CODFIC, PFC_CODPOB)
);
ALTER TABLE RSC_POBFIC ADD (
 CONSTRAINT RSC_PFCFIC_FK  FOREIGN KEY (PFC_CODFIC) REFERENCES RSC_FICHA (FIC_CODI)
);
ALTER TABLE RSC_POBFIC ADD (
 CONSTRAINT RSC_PFCPOB_FK  FOREIGN KEY (PFC_CODPOB) REFERENCES RSC_PUBOBJ (POB_CODI)
);

-- TAULA RSC_POBPRO
CREATE TABLE RSC_POBPRO(
  PPR_CODPRO  NUMBER(19) NOT NULL,
  PPR_CODPOB  NUMBER(19) NOT NULL
);
ALTER TABLE RSC_POBPRO ADD (
  CONSTRAINT RSC_POBPRO_PK  PRIMARY KEY  (PPR_CODPRO , PPR_CODPOB)
);
ALTER TABLE RSC_POBPRO ADD (
 CONSTRAINT RSC_PPRPRO_FK  FOREIGN KEY (PPR_CODPRO) REFERENCES RSC_PROCED (PRO_CODI)
);
ALTER TABLE RSC_POBPRO ADD (
  CONSTRAINT RSC_PPRPOB_FK  FOREIGN KEY (PPR_CODPOB) REFERENCES RSC_PUBOBJ (POB_CODI)
);

