-- canales de presentacion . 
ALTER TABLE RSC_TRAMIT ADD TRA_CTELEM bool DEFAULT FALSE;
ALTER TABLE RSC_TRAMIT ADD TRA_CPRESE bool DEFAULT FALSE;

ALTER TABLE RSC_SERVIC ADD SER_CTELEM bool DEFAULT FALSE;
ALTER TABLE RSC_SERVIC ADD SER_CPRESE bool DEFAULT FALSE;
ALTER TABLE RSC_SERVIC ADD SER_CTELEF bool DEFAULT FALSE;

COMMENT ON COLUMN RSC_TRAMIT.TRA_CTELEM is 'Canal telematico.';
COMMENT ON COLUMN RSC_TRAMIT.TRA_CPRESE is 'Canal presencial.';

COMMENT ON COLUMN RSC_SERVIC.SER_CTELEM is 'Canal telematico.';
COMMENT ON COLUMN RSC_SERVIC.SER_CPRESE is 'Canal presencial.';
COMMENT ON COLUMN RSC_SERVIC.SER_CTELEF is 'Canal telefonico.';

ALTER TABLE RSC_USUARI ADD USU_PERMISOS VARCHAR(512) SET DEFAULT 'P_MOD_NOR';
COMMENT ON COLUMN RSC_USUARI.USU_PERMISOS is 'Permisos separados por comas: P_MOD_NOR (modificacion de normativas)';