-- TAULA RSC_TRATRA
-- canvis de varchar a clob 
ALTER TABLE RSC_TRATRA ADD (TTR_DESCRI_2 CLOB);
UPDATE RSC_TRATRA SET TTR_DESCRI_2 = TTR_DESCRI;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_DESCRI;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_DESCRI_2 TO TTR_DESCRI;

ALTER TABLE RSC_TRATRA ADD (TTR_DOCUME_2 CLOB);
UPDATE RSC_TRATRA SET TTR_DOCUME_2 = TTR_DOCUME;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_DOCUME;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_DOCUME_2 TO TTR_DOCUME;


ALTER TABLE RSC_TRATRA ADD (TTR_REQUI_2 CLOB);
UPDATE RSC_TRATRA SET TTR_REQUI_2 = TTR_REQUI;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_REQUI;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_REQUI_2 TO TTR_REQUI;