-- TAULA RSC_TRATRA
-- canvis de varchar a clob 
ALTER TABLE RSC_TRATRA ADD (TTR_DESCRI_2 CLOB);
UPDATE RSC_TRATRA SET TTR_DESCRI_2 = TTR_DESCRI;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_DESCRI;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_DESCRI_2 TO TTR_DESCRI;

ALTER TABLE RSC_TRATRA ADD (TTR_DOCUME_2 CLOB);
UPDATE RSC_TRATRA SET TTR_DOCUME_2 = TTR_DOCUME;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_DOCUME;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_DOCUME_2 TO TTR_DOCUME;


ALTER TABLE RSC_TRATRA ADD (TTR_REQUI_2 CLOB);
UPDATE RSC_TRATRA SET TTR_REQUI_2 = TTR_REQUI;
ALTER TABLE RSC_TRATRA DROP COLUMN TTR_REQUI;
ALTER TABLE RSC_TRATRA RENAME COLUMN TTR_REQUI_2 TO TTR_REQUI;



-- TAULA RSC_TRAPRO
-- canvis de varchar a clob
ALTER TABLE RSC_TRAPRO ADD (TPR_RESUME_2 CLOB);
UPDATE RSC_TRAPRO SET TPR_RESUME_2 = TPR_RESUME;
ALTER TABLE RSC_TRAPRO DROP COLUMN TPR_RESUME;
ALTER TABLE RSC_TRAPRO RENAME COLUMN TPR_RESUME_2 TO TPR_RESUME;


ALTER TABLE RSC_TRAPRO ADD (TPR_DESTIN_2 CLOB);
UPDATE RSC_TRAPRO SET TPR_DESTIN_2 = TPR_DESTIN;
ALTER TABLE RSC_TRAPRO DROP COLUMN TPR_DESTIN;
ALTER TABLE RSC_TRAPRO RENAME COLUMN TPR_DESTIN_2 TO TPR_DESTIN;


ALTER TABLE RSC_TRAPRO ADD (TPR_REQUIS_2 CLOB);
UPDATE RSC_TRAPRO SET TPR_REQUIS_2 = TPR_REQUIS;
ALTER TABLE RSC_TRAPRO DROP COLUMN TPR_REQUIS;
ALTER TABLE RSC_TRAPRO RENAME COLUMN TPR_REQUIS_2 TO TPR_REQUIS;


ALTER TABLE RSC_TRAPRO ADD (TPR_OBSERV_2 CLOB);
UPDATE RSC_TRAPRO SET TPR_OBSERV_2 = TPR_OBSERV;
ALTER TABLE RSC_TRAPRO DROP COLUMN TPR_OBSERV;
ALTER TABLE RSC_TRAPRO RENAME COLUMN TPR_OBSERV_2 TO TPR_OBSERV;