ALTER TABLE RSC_PROCED ADD PRO_FUNHAB NUMBER(1,0) DEFAULT 0;
ALTER TABLE RSC_PROCED ADD PRO_APOHAB NUMBER(1,0) DEFAULT 0;

COMMENT ON COLUMN RSC_PROCED.PRO_FUNHAB IS 'CAMPO SIA Disponible Funcionario Habilitado';
COMMENT ON COLUMN RSC_PROCED.PRO_APOHAB IS 'CAMPO SIA Disponible Apoderado Habilitado';