/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;

public class Auditoria implements ValueObject {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Historico getHistorico() {
        return historico;
    }

    public void setHistorico(Historico historico) {
        this.historico = historico;
    }

    public int getCodigoOperacion() {
        return codigoOperacion;
    }

    public void setCodigoOperacion(int codigoOperacion) {
        this.codigoOperacion = codigoOperacion;
    }

    private Long id;
    private String usuario;
    private Date fecha;
    private Historico historico;
    private int codigoOperacion;

    public final static int INSERTAR = 1;
    public final static int MODIFICAR = 2;
    public final static int VALIDAR = 3;
    public final static int RESERVA = 4;
    public final static int BORRAR = 5;
    public final static int DESVALIDAR = 6;
}
