/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.HashSet;
import java.util.Set;

import org.ibit.rol.sac.model.ws.ArchivoTransferible;
import org.ibit.rol.sac.model.ws.EdificioTransferible;
import org.ibit.rol.sac.model.ws.ProcedimientoTransferible;

public class Edificio extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCodigoPostal() {
        return codigoPostal;
    }

    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public String getPoblacion() {
        return poblacion;
    }

    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Archivo getFotoPequenya() {
        return fotoPequenya;
    }

    public void setFotoPequenya(Archivo fotoPequenya) {
        this.fotoPequenya = fotoPequenya;
    }

    public Archivo getFotoGrande() {
        return fotoGrande;
    }

    public void setFotoGrande(Archivo fotoGrande) {
        this.fotoGrande = fotoGrande;
    }

    public Archivo getPlano() {
        return plano;
    }

    public void setPlano(Archivo plano) {
        this.plano = plano;
    }

    public Set getUnidadesAdministrativas() {
        return unidadesAdministrativas;
    }

    public void setUnidadesAdministrativas(Set unidadesAdministrativas) {
        this.unidadesAdministrativas = unidadesAdministrativas;
    }
    
    public String getLatitud() {
        return latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    
    public String getLongitud() {
        return longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }


    private Long id;
    private String direccion;
    private String codigoPostal;
    private String poblacion;
    private String telefono;
    private String fax;
    private String email;
    private Archivo fotoPequenya;
    private Archivo fotoGrande;
    private Archivo plano;
    private Set unidadesAdministrativas = new HashSet();
    private String latitud;
    private String longitud;
  

    
}
