/* Generated by Together */

package org.ibit.rol.sac.model;

public class Historico implements ValueObject {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    private Long id;
    private String nombre;
}
