/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Modificado para (PORMAD)
 */

public class Materia extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getProcedimientosLocales() {
        return procedimientosLocales;
    }

    public void setProcedimientosLocales(Set procedimientosLocales) {
        this.procedimientosLocales = procedimientosLocales;
    }

    public Set getUnidadesmaterias() {
        return unidadesmaterias;
    }

    public void setUnidadesmaterias(Set unidadesmaterias) {
        this.unidadesmaterias = unidadesmaterias;
    }

    public String getCodiHita() {
        return codiHita;
    }

    public void setCodiHita(String codiHita) {
        this.codiHita = codiHita;
    }

    public Set getFichas() {
        return fichas;
    }

    public void setFichas(Set fichas) {
        this.fichas = fichas;
    }

    public Set getIconos() {
        return iconos;
    }

    public void setIconos(Set iconos) {
        this.iconos = iconos;
    }

    public void addIcono(IconoMateria icono) {
        icono.setMateria(this);
        iconos.add(icono);
    }

    public void removeIcono(IconoMateria icono) {
        iconos.remove(icono);
    }

     public String getCodigoEstandar() {
        return codigoEstandar;
    }

    public void setCodigoEstandar(String codigoEstandar) {
        this.codigoEstandar = codigoEstandar;
    }

    public void addUnidadMateria(UnidadMateria unidadMateria) {
        unidadMateria.setMateria(this);
        unidadesmaterias.add(unidadMateria);
    }

    public void removeUnidadMateria(UnidadMateria unidadMateria) {
        unidadesmaterias.remove(unidadMateria);
    }
    
    public Archivo getFoto() {
		return foto;
	}

	public void setFoto(Archivo foto) {
		this.foto = foto;
	}

	public Archivo getIcono() {
		return icono;
	}

	public void setIcono(Archivo icono) {
		this.icono = icono;
	}

	public Archivo getIconoGrande() {
		return iconoGrande;
	}

	public void setIconoGrande(Archivo iconoGrande) {
		this.iconoGrande = iconoGrande;
	}

    public boolean isDestacada() {
        return destacada;
    }

    public void setDestacada(boolean destacada) {
        this.destacada = destacada;
    }
    
    public void addMateriaAgrupacionM(MateriaAgrupacionM mata) {
    	mata.setMateria(this);
    	materiasAgrupacionM.add(mata);
    }

    public void removeMateriaAgrupacionM(MateriaAgrupacionM mata) {
    	mata.setMateria(null);
        materiasAgrupacionM.remove(mata);
    }
    
	public Set<MateriaAgrupacionM> getMateriasAgrupacionM() {
		return materiasAgrupacionM;
	}

	public void setMateriasAgrupacionM(Set<MateriaAgrupacionM> materiasAgrupacionM) {
		this.materiasAgrupacionM = materiasAgrupacionM;
	}
    

    private Long id;
    private String codiHita;
    private Set procedimientosLocales;
    private Set unidadesmaterias;
    private Set fichas;
    private Set iconos;
    private Archivo icono;
    private Archivo iconoGrande;
    private Archivo foto;
    private String codigoEstandar;
    private boolean destacada;
    private Set<MateriaAgrupacionM> materiasAgrupacionM;


}
