/* Generated by Together */

package org.ibit.rol.sac.model;

public class Validacion {

    public final static Integer PUBLICA = new Integer(1);
    public final static Integer INTERNA = new Integer(2);
    public final static Integer RESERVA = new Integer(3);
    public final static Integer BAJA = new Integer(4);
}
