/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;




public class ActivacionSuscripcion extends Traducible{

 
    private String email;
    private String idImagen;
    private String clave;
    private Short numeroEnvios;
    private Date fechaEnvio;
    
    private TipoSuscripcion tipoSuscripcion;

 

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaEnvio() {
		return fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public String getIdImagen() {
		return idImagen;
	}

	public void setIdImagen(String idImagen) {
		this.idImagen = idImagen;
	}

	public Short getNumeroEnvios() {
		return numeroEnvios;
	}

	public void setNumeroEnvios(Short numeroEnvios) {
		this.numeroEnvios = numeroEnvios;
	}

	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}


}
