/* Generated by Together */

package org.ibit.rol.sac.model;

import org.ibit.rol.sac.model.ws.ArchivoTransferible;

public class Archivo implements ValueObject {

	private Long id;
	private String mime;
	private String nombre;
	private long peso;
	private byte[] datos;

	public Archivo() {
    }

    public Archivo(Long id, String mime, String nombre, long peso) {
        this.id = id;
        this.mime = mime;
        this.nombre = nombre;
        this.peso = peso;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMime() {
        return mime;
    }

    public void setMime(String mime) {
        this.mime = mime;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public long getPeso() {
        return peso;
    }

    public void setPeso(long peso) {
        this.peso = peso;
    }

    public byte[] getDatos() {
        return datos;
    }

    public void setDatos(byte[] datos) {
        this.datos = datos;
    }
    
    public static Archivo generar(final ArchivoTransferible archivoTransferible){
    	Archivo archivo = null;
    	
    	if(archivoTransferible!=null){
	    	archivo = new Archivo();
			archivo.setDatos(archivoTransferible.getDatos());
			archivo.setMime(archivoTransferible.getMime());
			archivo.setNombre(archivoTransferible.getNombre());
			if(archivoTransferible.getPeso()!=null){
				archivo.setPeso(archivoTransferible.getPeso());
			}else{
				archivo.setPeso(archivoTransferible.getDatos().length);
			}
    	}
    	return archivo;
    }

	@Override
	public String toString() {
		return "Archivo [id=" + id + ", mime=" + mime + ", nombre=" + nombre
				+ ", peso=" + peso + "]";
	}
    
}
