/* Generated by Together */

package org.ibit.rol.sac.model;

import org.ibit.rol.sac.model.ws.ArchivoTransferible;

public class ArchivoResumen implements ValueObject {

	private Long id;
	private String mime;
	private String nombre;
	private long peso;

	public ArchivoResumen() {
    }

    public ArchivoResumen(Long id, String mime, String nombre) {
        this.id = id;
        this.mime = mime;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMime() {
        return mime;
    }

    public void setMime(String mime) {
        this.mime = mime;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public long getPeso() {
        return peso;
    }

    public void setPeso(long peso) {
        this.peso = peso;
    }
    
    public static ArchivoResumen generar(final ArchivoTransferible archivoTransferible){
    	ArchivoResumen archivoResumen = null;
    	
    	if(archivoTransferible!=null){
	    	archivoResumen = new ArchivoResumen();
//			archivoResumen.setDatos(archivoTransferible.getDatos());
			archivoResumen.setMime(archivoTransferible.getMime());
			archivoResumen.setNombre(archivoTransferible.getNombre());
			if(archivoTransferible.getPeso()!=null){
				archivoResumen.setPeso(archivoTransferible.getPeso());
//			}else{
//				archivo.setPeso(archivoTransferible.getDatos().length);
			}
    	}
    	return archivoResumen;
    }

	@Override
	public String toString() {
		return "Archivo [id=" + id + ", mime=" + mime + ", nombre=" + nombre
				+ ", peso=" + peso + "]";
	}

    
}
