/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;

public class CatalegDocuments extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrdre() {
		return ordre;
	}

	public void setOrdre(Long ordre) {
		this.ordre = ordre;
	}

	public Integer getAdmResponsable() {
		return admResponsable;
	}

	public void setAdmResponsable(Integer admResponsable) {
		this.admResponsable = admResponsable;
	}

	public Set getDoctramite() {
		return doctramite;
	}

	public void setDoctramite(Set doctramite) {
		this.doctramite = doctramite;
	}

	public ExcepcioDocumentacio getExcepcioDocumentacio() {
		return excepcioDocumentacio;
	}

	public void setExcepcioDocumentacio(ExcepcioDocumentacio excepcioDocumentacio) {
		this.excepcioDocumentacio = excepcioDocumentacio;
	}


	private Long id;
    private Long ordre;
    private Integer admResponsable;    
    private Set doctramite;
    private ExcepcioDocumentacio excepcioDocumentacio;
}
