/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Iterator;

 public class ElementOrdenat extends Traducible implements Indexable {

    private Long id;

    private Long orden;


	
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

     public Long getOrden() {
        return orden;
    }

    public void setOrden(Long orden) {
        this.orden = orden;
    }



    @Override
    public boolean equals(Object obj) {
    	return (obj instanceof ElementOrdenat && (id==((ElementOrdenat)obj).id));
    } 

	@Override
	public String toString() {
		return "ElementOrdenat [id="+ id + ", orden=" + orden +"]";
	}

	

}
