/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Iterator;

 public class ElementOrdenat extends Traducible implements Indexable {

    private Long id;

    private Long orden;


	
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

     public Long getOrden() {
        return orden;
    }

    public void setOrden(Long orden) {
        this.orden = orden;
    }

    
    
    public IndexObject indexObject() {
        final IndexObject io = new IndexObject();
    //    io.setId(id);
    //    io.setClassName(Documento.class.getName());
        for (Iterator iterator = getTraducciones().values().iterator(); iterator.hasNext();) {
            TraduccionElementOrdenat tr = (TraduccionElementOrdenat) iterator.next();
            if (tr != null) {
                io.addTextLine(tr.getTitulo());
                io.addTextLine(tr.getDescripcion());
            }
        }

        return io;
    } 

    @Override
    public boolean equals(Object obj) {
    	return (obj instanceof ElementOrdenat && (id==((ElementOrdenat)obj).id));
    } 

	@Override
	public String toString() {
		return "ElementOrdenat [id="+ id + ", orden=" + orden +"]";
	}

	

}
