/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class EnvioSuscripcion implements ValueObject {
	
	public static final String EJECUTADO = "E";
	public static final String GENERACION = "G";
	public static final String PENDIENTE = "P";

	public static final String CANAL_MENSAJE = "M";
	public static final String CANAL_SMS = "S";

	public static final String TIPO_BOLETIN = "B";
	public static final String TIPO_ALERTAS = "A";
	public static final String TIPO_ESTUDIOS = "E";

	private Long id;
    private Date fechaEnvio;
    private String canalEnvio;
    private String asunto;
    private String contenidoHtml;
    private String tipo;
    private String titulo;
    private Long seccion;
    private String estado;
    private Date fechaEnviado;
    private Date fechaAlta;
    private Long usuarioAlta;
    private Date fechaModificacion;
    private Long usuarioModificacion;
    private Date fechaBaja;

    private TipoSuscripcion tipoSuscripcion;


	private Set grupos = new HashSet();

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAsunto() {
		return asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getCanalEnvio() {
		return canalEnvio;
	}

	public void setCanalEnvio(String canalEnvio) {
		this.canalEnvio = canalEnvio;
	}

	public String getContenidoHtml() {
		return contenidoHtml;
	}

	public void setContenidoHtml(String contenidoHtml) {
		this.contenidoHtml = contenidoHtml;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public Date getFechaEnviado() {
		return fechaEnviado;
	}

	public void setFechaEnviado(Date fechaEnviado) {
		this.fechaEnviado = fechaEnviado;
	}

	public Date getFechaEnvio() {
		return fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set getGrupos() {
		return grupos;
	}

	public void setGrupos(Set grupos) {
		this.grupos = grupos;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSeccion() {
		return seccion;
	}

	public void setSeccion(Long seccion) {
		this.seccion = seccion;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Long getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Long usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Long getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Long usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}



}
