/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;

public class Familia extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getProcedimientosLocales() {
        return procedimientosLocales;
    }

    public void setProcedimientosLocales(Set procedimientosLocales) {
        this.procedimientosLocales = procedimientosLocales;
    }

    public Set getIconos() {
        return iconos;
    }

    public void setIconos(Set iconos) {
        this.iconos = iconos;
    }

    public void addIcono(IconoFamilia icono) {
        icono.setFamilia(this);
        iconos.add(icono);
    }

    public void removeIcono(IconoFamilia icono) {
        iconos.remove(icono);
    }


    private Long id;
    private Set procedimientosLocales;
    private Set iconos;
}
