/* Generated by Together */

package org.ibit.rol.sac.model;


public class Formulario implements ValueObject {

	  private Long id;
	    private String nombre;
	    private String url;
	    private Archivo archivo;
	    private String urlManual;
	    private Archivo manual;
	    private Tramite tramite;
	
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    public String getUrlManual() {
        return urlManual;
    }

    public void setUrlManual(String urlManual) {
        this.urlManual = urlManual;
    }

    public Archivo getManual() {
        return manual;
    }

    public void setManual(Archivo manual) {
        this.manual = manual;
    }

    public Tramite getTramite() {
        return tramite;
    }

    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }

  
	@Override
	public String toString() {
		String tramiteId=null==this.tramite? null: this.tramite.getId().toString() ;
		return "Formulario [archivo=" + archivo + ", id=" + id + ", manual="
				+ manual + ", nombre=" + nombre + ", tramite=" + tramiteId
				+ ", url=" + url + ", urlManual=" + urlManual + "]";
	}
    
    
}
