/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.HashSet;
import java.util.Set;




public class GrupoSuscripcion extends Traducible{

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getSuscriptores() {
		return suscriptores;
	}

	public void setSuscriptores(Set suscriptores) {
		this.suscriptores = suscriptores;
	}


    private Long id;
    private String identificador;
    
    private TipoSuscripcion tipoSuscripcion;

    
	private Set suscriptores = new HashSet();
	
	public void addSuscriptor(Suscriptor s){
		s.setGrupo(this);
		suscriptores.add(s);
	}
	
	public void removeSuscriptor(Suscriptor s){
		suscriptores.remove(s);
	}




	public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GrupoSuscripcion)) return false;

        final GrupoSuscripcion grupoSuscripcion = (GrupoSuscripcion) o;

        if (id != null ? !id.equals(grupoSuscripcion.id) : grupoSuscripcion.id != null) return false;

        return true;
    }

    public int hashCode() {
        return (id != null ? id.hashCode() : 0);
    }

	public String getIdentificador() {
		return identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public void addTraduccionMap(String lang, TraduccionGrupoSuscripcion traduccion) {
        setTraduccion(lang, traduccion);
    }	
	
	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}


}
