/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.HashSet;
import java.util.Set;




public class GrupoGenericoSuscripcion extends Traducible{

	public static final Integer ESTUDIOS = new Integer(1);

	public static final Integer PROFESION = new Integer(2);

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getSuscriptores() {
		return suscriptores;
	}

	public void setSuscriptores(Set suscriptores) {
		this.suscriptores = suscriptores;
	}


    private Long id;
    private Integer tipo;
    
    private TipoSuscripcion tipoSuscripcion;

    
	private Set suscriptores = new HashSet();
	





	public Integer getTipo() {
		return tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GrupoGenericoSuscripcion)) return false;

        final GrupoGenericoSuscripcion grupoSuscripcion = (GrupoGenericoSuscripcion) o;

        if (id != null ? !id.equals(grupoSuscripcion.id) : grupoSuscripcion.id != null) return false;

        return true;
    }

    public int hashCode() {
        return (id != null ? id.hashCode() : 0);
    }



	public void addTraduccionMap(String lang, TraduccionGrupoGenericoSuscripcion traduccion) {
        setTraduccion(lang, traduccion);
    }	
	
	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}


}
