/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.List;
import java.util.Set;

public class HechoVital extends Traducible {

	private static final long serialVersionUID = 1L;
	
	private Long id;
    private int orden;
    private Archivo icono;
    private Archivo iconoGrande;
    private Archivo foto;
    private List<HechoVitalProcedimiento> hechosVitalesProcedimientos;
    private String codigoEstandar;
    private Set<Ficha> fichas;
    private Set<HechoVitalAgrupacionHV> hechosVitalesAgrupacionHV;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getOrden() {
        return orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public Archivo getIcono() {
        return icono;
    }

    public void setIcono(Archivo icono) {
        this.icono = icono;
    }

    public Archivo getIconoGrande() {
		return iconoGrande;
	}

	public void setIconoGrande(Archivo iconoGrande) {
		this.iconoGrande = iconoGrande;
	}
	
	public Archivo getFoto() {
		return foto;
	}

	public void setFoto(Archivo foto) {
		this.foto = foto;
	}

	public List getHechosVitalesProcedimientos() {
        return hechosVitalesProcedimientos;
    }

    public void setHechosVitalesProcedimientos(List<HechoVitalProcedimiento> hechosVitalesProcedimientos) {
        this.hechosVitalesProcedimientos = hechosVitalesProcedimientos;
    }

    public void addHechoVitalProcedimiento(HechoVitalProcedimiento hpv) {
        hpv.setHechoVital(this);
        hpv.setOrden(hechosVitalesProcedimientos.size());
        hechosVitalesProcedimientos.add(hpv);
    }
    
    public void addHechoVitalProcedimientoRespetandoOrden(HechoVitalProcedimiento hpv) {
        hpv.setHechoVital(this);
        hechosVitalesProcedimientos.add(hpv);
    }

    public void removeHechoVitalProcedimiento(HechoVitalProcedimiento hechovp){
        int index = hechosVitalesProcedimientos.indexOf(hechovp);
        if (index > -1) {
            hechosVitalesProcedimientos.remove(index);
            for (int i = index; i < hechosVitalesProcedimientos.size(); i++) {
                HechoVitalProcedimiento hvp = (HechoVitalProcedimiento) hechosVitalesProcedimientos.get(i);
                if (hvp != null) {
                	hvp.setOrden(i);
                }
            }
        }
    }

    public String getCodigoEstandar() {
        return codigoEstandar;
    }

    public void setCodigoEstandar(String codigoEstandar) {
        this.codigoEstandar = codigoEstandar;
    }

     public Set getFichas() {
        return fichas;
    }

    public void setFichas(Set<Ficha> fichas) {
        this.fichas = fichas;
    }

    public Set<HechoVitalAgrupacionHV> getHechosVitalesAgrupacionHV() {
        return hechosVitalesAgrupacionHV;
    }

    public void setHechosVitalesAgrupacionHV(Set<HechoVitalAgrupacionHV> agrupaciones) {
        this.hechosVitalesAgrupacionHV = agrupaciones;
    }
    
    public void addHechoVitalAgrupacionHV(HechoVitalAgrupacionHV hva) {
    	hva.setHechoVital(this);
        hechosVitalesAgrupacionHV.add(hva);
    }

    public void removeHechoVitalAgrupacionHV(HechoVitalAgrupacionHV hechova) {
        hechova.setHechoVital(null);
        hechosVitalesAgrupacionHV.remove(hechova);
    }

}
