/* Generated by Together */

package org.ibit.rol.sac.model;


public class HistoricoUA extends Historico {

    public UnidadAdministrativa getUa() {
        return ua;
    }

    public void setUa(UnidadAdministrativa ua) {
        this.ua = ua;
    }

    private UnidadAdministrativa ua;
}
