/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


public class HistoricoEnvio implements ValueObject {
	
	private Long id;
    private Date fechaEnvio;

    private TipoSuscripcion tipoSuscripcion;

	private Set temas = new HashSet();
	


	public Set getTemas() {
		return temas;
	}

	public void setTemas(Set temas) {
		this.temas = temas;
	}
	
	public void addTema(RegistroTemaEnvio tema)
	{
		tema.setEnvio(this);
		temas.add(tema);
	}

	public void removeTema(RegistroTemaEnvio tema)
	{
		tema.setEnvio(null);
		temas.remove(tema);
	}

	public Date getFechaEnvio() {
		return fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}


}
