/* Generated by Together */

package org.ibit.rol.sac.model;


public class HistoricoNormativa extends Historico {

    public Normativa getNormativa() {
        return normativa;
    }

    public void setNormativa(Normativa normativa) {
        this.normativa = normativa;
    }

    private Normativa normativa;
}
