/* Generated by Together */

package org.ibit.rol.sac.model;

/**
 * Historico servicio.
 * @author slromero
 *
 */
public class HistoricoServicio extends Historico {

	/** Serial version UID. **/
	private static final long serialVersionUID = 1L;
	
	/** Servicio. **/
    private Servicio servicio;

	/**
	 * @return the servicio
	 */
	public Servicio getServicio() {
		return servicio;
	}

	/**
	 * @param servicio the servicio to set
	 */
	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}
    
}
