/* Generated by Together */

package org.ibit.rol.sac.model;


public class HistoricoFicha extends Historico {

    private Ficha ficha;
    private Materia materia;
	private UnidadAdministrativa ua;
	
    public Ficha getFicha() {
        return ficha;
    }

    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

	public Materia getMateria() {
		return materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	public UnidadAdministrativa getUa() {
		return ua;
	}

	public void setUa(UnidadAdministrativa ua) {
		this.ua = ua;
	}
    
}
