/* Generated by Together */

package org.ibit.rol.sac.model;


public class HistoricoProcedimiento extends Historico {

    public ProcedimientoLocal getProcedimiento() {
        return procedimiento;
    }

    public void setProcedimiento(ProcedimientoLocal procedimiento) {
        this.procedimiento = procedimiento;
    }

    private ProcedimientoLocal procedimiento;
}
