/* Generated by Together */

package org.ibit.rol.sac.model;

public class IconoFamilia implements ValueObject {
	
	private static final long serialVersionUID = 1L;
	
	private Long id;
    private Familia familia;
    private PerfilCiudadano perfil;
    private Archivo icono;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Familia getFamilia() {
        return familia;
    }

    public void setFamilia(Familia familia) {
        this.familia = familia;
    }

    public PerfilCiudadano getPerfil() {
        return perfil;
    }

    public void setPerfil(PerfilCiudadano perfil) {
        this.perfil = perfil;
    }

    public Archivo getIcono() {
        return icono;
    }

    public void setIcono(Archivo icono) {
        this.icono = icono;
    }
    
}
