/* Generated by Together */

package org.ibit.rol.sac.model;

public class IconoMateria implements ValueObject {
	
	private Long id;
    private Materia materia;
    private PerfilCiudadano perfil;
    private Archivo icono;
    private String nombre;

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Materia getMateria() {
        return materia;
    }

    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    public PerfilCiudadano getPerfil() {
        return perfil;
    }

    public void setPerfil(PerfilCiudadano perfil) {
        this.perfil = perfil;
    }

    public Archivo getIcono() {
        return icono;
    }

    public void setIcono(Archivo icono) {
        this.icono = icono;
    }
    
    public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
    
    public IconoMateria() {
		super();
	}
    
    public IconoMateria(Long id, String nombre) {
    	
    	this.id = id;
    	this.nombre = nombre;
    	
    }
    
}
