 /* Generated by Together */
package org.ibit.rol.sac.model;

import java.util.Set;

 
 
public class Iniciacion extends Traducible {


	public Set getProcedimientosLocales() {
	        return procedimientosLocales;
	    }

	public void setProcedimientosLocales(Set procedimientosLocales) {
	        this.procedimientosLocales = procedimientosLocales;
	    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigoEstandar() {
        return codigoEstandar;
    }

    public void setCodigoEstandar(String codigoEstandar) {
        this.codigoEstandar = codigoEstandar;
    }

    private Long id;
    private Set procedimientosLocales;
    private String codigoEstandar;
}
