/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Iterator;


public class NormativaExterna extends Normativa implements Indexable {

	/*
    public IndexObject indexObject() {
        final IndexObject io = super.indexObject();
        for (Iterator iterator = getTraducciones().values().iterator(); iterator.hasNext();) {
            TraduccionNormativaExterna tr = (TraduccionNormativaExterna) iterator.next();
            if (tr != null) {
                io.addTextLine(tr.getApartado());
                io.addTextLine(tr.getObservaciones());
                io.addTextLine(tr.getResponsable());
                io.addTextLine(tr.getSeccion());
                io.addTextLine(tr.getTitulo());
                io.addArchivo(tr.getArchivo());
            }
        }
        return io;
    }
    */
}
