/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;

public class PerfilCiudadano extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigoEstandard() {
        return codigoEstandard;
    }

    public void setCodigoEstandard(String codigoEstandard) {
        this.codigoEstandard = codigoEstandard;
    }

    public String getPathIconografia() {
        return pathIconografia;
    }

    public void setPathIconografia(String pathIconografia) {
        this.pathIconografia = pathIconografia;
    }

    public Set getIconosFamilia() {
        return iconosFamilia;
    }

    public void setIconosFamilia(Set iconosFamilia) {
        this.iconosFamilia = iconosFamilia;
    }

    public Set getIconosMateria() {
        return iconosMateria;
    }

    public void setIconosMateria(Set iconosMateria) {
        this.iconosMateria = iconosMateria;
    }

    public void addIconoFamilia(IconoFamilia icono) {
        icono.setPerfil(this);
        iconosFamilia.add(icono);
    }

    public void removeIconoFamilia(IconoFamilia icono) {
        iconosFamilia.remove(icono);
    }

    public void addIconoMateria(IconoMateria icono) {
        icono.setPerfil(this);
        iconosMateria.add(icono);
    }

    public void removeIconoMateria(IconoMateria icono) {
        iconosMateria.remove(icono);
    }

    private Long id;
    private String codigoEstandard;
    private String pathIconografia;
    private Set iconosFamilia;
    private Set iconosMateria;
}
