/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;

public interface Procedimiento extends ValueObject {
	
	public static final Integer ESTADO_PUBLICACION_PUBLICA = 1;
	public static final Integer ESTADO_PUBLICACION_INTERNA = 2;
	public static final Integer ESTADO_PUBLICACION_RESERVA = 3;

    String getSignatura();

    void setSignatura(String signatura);

    Date getFechaCaducidad();

    void setFechaCaducidad(Date fechaCaducidad);

    Date getFechaPublicacion();

    void setFechaPublicacion(Date fechaPublicacion);

    Date getFechaActualizacion();

    void setFechaActualizacion(Date fechaActualizacion);
}
