/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;
import java.util.List;
import java.util.Date;

public interface Procedimiento extends ValueObject {

    String getSignatura();

    void setSignatura(String signatura);

    Date getFechaCaducidad();

    void setFechaCaducidad(Date fechaCaducidad);

    Date getFechaPublicacion();

    void setFechaPublicacion(Date fechaPublicacion);

    Date getFechaActualizacion();

    void setFechaActualizacion(Date fechaActualizacion);
}
