/* Generated by Together */

package org.ibit.rol.sac.model;


public class RegistroTemaSuscriptor implements ValueObject {
	
	private Long idMateria;

	public Long getIdMateria() {
		return idMateria;
	}

	public void setIdMateria(Long idMateria) {
		this.idMateria = idMateria;
	}


}
