/* Generated by Together */

package org.ibit.rol.sac.model;



public class RequisitTramit extends ElementTramit  {

	@Override
	public String toString() {

		return "RequisitTramit [" +super.toString()+"]";
	}

}
