/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;
import java.util.List;

public class Seccion extends Traducible implements Comparable {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigoEstandard() {
        return codigoEstandard;
    }

    public void setCodigoEstandard(String codigoEstandard) {
        this.codigoEstandard = codigoEstandard;
    }

    public Seccion getPadre() {
        return padre;
    }

    public void setPadre(Seccion padre) {
        this.padre = padre;
    }

    public List getHijos() {
        return hijos;
    }

    public void setHijos(List hijos) {
        this.hijos = hijos;
    }

    public String getPerfil() {
        return perfil;
    }

    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    public int getOrden() {
        return orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public Set getFichasUA() {
        return fichasUA;
    }

    public void setFichasUA(Set fichasUA) {
        this.fichasUA = fichasUA;
    }

    public void addHijo(Seccion hijo) {
        if (!hijos.contains(hijo)) {
            if (hijo.getPadre() != null) {
                hijo.getPadre().removeHijo(hijo);
            }
            hijo.setPadre(this);
            hijo.setOrden(hijos.size());
            hijos.add(hijo);
        }
    }

    public void removeHijo(Seccion hijo) {
    	hijo.setPadre(null);
    	hijos.remove(hijo);
    	for (int i = 0; i < hijos.size(); i++) {
    		Seccion seccion = (Seccion) hijos.get(i);
    		seccion.setOrden(i);
    	}
    }

    public void addFichaUA(FichaUA ficha) {
        ficha.setSeccion(this);
        fichasUA.add(ficha);
    }

    public void removeFichaUA(FichaUA ficha) {
        fichasUA.remove(ficha);
        ficha.setSeccion(null);
    }

    private Long id;
    private String codigoEstandard;
    private Seccion padre;
    private List hijos;
    private String perfil;
    private int orden;
    private Set fichasUA;



    public int compareTo(Object o) {
        Seccion other = (Seccion) o;
        return this.getOrden() - other.getOrden();
    }
    
    public String toString(){
		StringBuffer salida = new StringBuffer("---Sección---\n");
		salida.append("  -id: ");
		salida.append(id);
		salida.append("\n -nombre");
		if (getTraduccion() != null)
			salida.append(((TraduccionSeccion)getTraduccion()).getNombre());
		salida.append("\n  -descripción: ");
		if(getTraduccion() != null)
			salida.append(((TraduccionSeccion)getTraduccion()).getDescripcion());
		salida.append("\n");
		return salida.toString();
	}
  
}
