/* Generated by Together */

package org.ibit.rol.sac.model;


public class SilencioAdm extends Traducible {


    private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
 
	 public String getNombreSilencio(String idioma) {
	        TraduccionSilencio tet = (TraduccionSilencio) getTraduccion(idioma);
	        return tet == null ? null : tet.getNombre();
	    }
}
