/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;
import java.util.Set;
import java.util.List;

public class SuscriptorClave implements ValueObject {

	private Long id;
	private String email;
    private String imagen;
    private String activacion;
    private Date fechaEnvio;
    private Long numeroEnvio;

    private TipoSuscripcion tipoSuscripcion;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }    
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

	public String getImagen() {
		return imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public String getActivacion() {
		return activacion;
	}

	public void setActivacion(String activacion) {
		this.activacion = activacion;
	}

	public Date getFechaEnvio() {
		return fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Long getNumeroEnvio() {
		return numeroEnvio;
	}

	public void setNumeroEnvio(Long numeroEnvio) {
		this.numeroEnvio = numeroEnvio;
	}

		public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}
}
