/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class Suscriptor implements ValueObject {

	public static final String TIPO_ACTIVO = "A"; 
	public static final String TIPO_PENDIENTE_ACTIVAR = "P"; 
	public static final String TIPO_BAJA = "B"; 

	public static final String TIPO_PARTICULAR = "P"; 
	public static final String TIPO_ENTIDAD_PUBLICA = "A"; 
	public static final String TIPO_ENTIDAD_PRIVADA = "E"; 

	public static final String SI = "S"; 
	public static final String NO = "N"; 

	public static final String ORIGEN_TELEMATICO = "T"; 
	public static final String ORIGEN_MANUAL = "M"; 
	
	public static final String VARON = "V"; 
	public static final String HEMBRA = "H"; 


	private Long id;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String email;
    private String sms;
    private String telefono;
    private String tipo;
    private String nombreEntidad;
    private String nombreArea;
    private String departamentoEntidad;
    private String cargo;
    private String boletin;
    private String alertas;
    private String estudios;
    private String estado;
    private String origen;
    private String referenciaTramite;
    private Long usuarioAlta;
    private Date fechaAlta;
    private Date fechaModificacion;
    private Date fechaBaja;


    private String sexo;
    private Integer anyoNacimiento;
    private Integer paisNacimiento;
    private Integer provinciaNacimiento;
    private Integer islaNacimiento;
    private Integer municipioNacimiento;
    private String lugarNacimientoOtros;
    private Integer paisResidencia;
    private Integer provinciaResidencia;
    private Integer islaResidencia;
    private Integer municipioResidencia;
    private String idioma;
    private String cif;
    private String sedeSocial;
    private String razonSocial;
    private String codigoPostal;
    private String contacto;
    private String nombreGrupo;
    private String resumenTemas;
    private String motivoBaja;

    private GrupoGenericoSuscripcion grupoEstudios;
    private GrupoGenericoSuscripcion grupoProfesion;    
    private TipoSuscripcion tipoSuscripcion;

    private GrupoSuscripcion grupo;

	private Set temas = new HashSet();
	




	public Integer getAnyoNacimiento() {
		return anyoNacimiento;
	}

	public void setAnyoNacimiento(Integer anyoNacimiento) {
		this.anyoNacimiento = anyoNacimiento;
	}

	public String getCif() {
		return cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	public String getCodigoPostal() {
		return codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getContacto() {
		return contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public GrupoGenericoSuscripcion getGrupoEstudios() {
		return grupoEstudios;
	}

	public void setGrupoEstudios(GrupoGenericoSuscripcion grupoEstudios) {
		this.grupoEstudios = grupoEstudios;
	}

	public GrupoGenericoSuscripcion getGrupoProfesion() {
		return grupoProfesion;
	}

	public void setGrupoProfesion(GrupoGenericoSuscripcion grupoProfesion) {
		this.grupoProfesion = grupoProfesion;
	}

	public String getIdioma() {
		return idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public Integer getIslaNacimiento() {
		return islaNacimiento;
	}

	public void setIslaNacimiento(Integer islaNacimiento) {
		this.islaNacimiento = islaNacimiento;
	}

	public Integer getIslaResidencia() {
		return islaResidencia;
	}

	public void setIslaResidencia(Integer islaResidencia) {
		this.islaResidencia = islaResidencia;
	}

	public String getLugarNacimientoOtros() {
		return lugarNacimientoOtros;
	}

	public void setLugarNacimientoOtros(String lugarNacimientoOtros) {
		this.lugarNacimientoOtros = lugarNacimientoOtros;
	}

	public String getMotivoBaja() {
		return motivoBaja;
	}

	public void setMotivoBaja(String motivoBaja) {
		this.motivoBaja = motivoBaja;
	}

	public Integer getMunicipioNacimiento() {
		return municipioNacimiento;
	}

	public void setMunicipioNacimiento(Integer municipioNacimiento) {
		this.municipioNacimiento = municipioNacimiento;
	}

	public Integer getMunicipioResidencia() {
		return municipioResidencia;
	}

	public void setMunicipioResidencia(Integer municipioResidencia) {
		this.municipioResidencia = municipioResidencia;
	}

	public String getNombreGrupo() {
		return nombreGrupo;
	}

	public void setNombreGrupo(String nombreGrupo) {
		this.nombreGrupo = nombreGrupo;
	}

	public Integer getPaisNacimiento() {
		return paisNacimiento;
	}

	public void setPaisNacimiento(Integer paisNacimiento) {
		this.paisNacimiento = paisNacimiento;
	}

	public Integer getPaisResidencia() {
		return paisResidencia;
	}

	public void setPaisResidencia(Integer paisResidencia) {
		this.paisResidencia = paisResidencia;
	}

	public Integer getProvinciaNacimiento() {
		return provinciaNacimiento;
	}

	public void setProvinciaNacimiento(Integer provinciaNacimiento) {
		this.provinciaNacimiento = provinciaNacimiento;
	}

	public Integer getProvinciaResidencia() {
		return provinciaResidencia;
	}

	public void setProvinciaResidencia(Integer provinciaResidencia) {
		this.provinciaResidencia = provinciaResidencia;
	}

	public String getRazonSocial() {
		return razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getResumenTemas() {
		return resumenTemas;
	}

	public void setResumenTemas(String resumenTemas) {
		this.resumenTemas = resumenTemas;
	}

	public String getSedeSocial() {
		return sedeSocial;
	}

	public void setSedeSocial(String sedeSocial) {
		this.sedeSocial = sedeSocial;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getAlertas() {
		return alertas;
	}

	public void setAlertas(String alertas) {
		this.alertas = alertas;
	}

	public String getApellido1() {
		return apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getBoletin() {
		return boletin;
	}

	public void setBoletin(String boletin) {
		this.boletin = boletin;
	}

	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getNombreArea() {
		return nombreArea;
	}

	public void setNombreArea(String nombreArea) {
		this.nombreArea = nombreArea;
	}

	public String getDepartamentoEntidad() {
		return departamentoEntidad;
	}

	public void setDepartamentoEntidad(String departamentoEntidad) {
		this.departamentoEntidad = departamentoEntidad;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getEstudios() {
		return estudios;
	}

	public void setEstudios(String estudios) {
		this.estudios = estudios;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public GrupoSuscripcion getGrupo() {
		return grupo;
	}

	public void setGrupo(GrupoSuscripcion grupo) {
		this.grupo = grupo;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreEntidad() {
		return nombreEntidad;
	}

	public void setNombreEntidad(String nombreEntidad) {
		this.nombreEntidad = nombreEntidad;
	}

	public String getOrigen() {
		return origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getReferenciaTramite() {
		return referenciaTramite;
	}

	public void setReferenciaTramite(String referenciaTramite) {
		this.referenciaTramite = referenciaTramite;
	}

	public String getSms() {
		return sms;
	}

	public void setSms(String sms) {
		this.sms = sms;
	}

	public String getTipo() {
		return tipo;
	}

	public String getTelefono() {
		return telefono;
	}
	
	public void setTelefono(String telf) {
		this.telefono = telf;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public TipoSuscripcion getTipoSuscripcion() {
		return tipoSuscripcion;
	}

	public void setTipoSuscripcion(TipoSuscripcion tipoSuscripcion) {
		this.tipoSuscripcion = tipoSuscripcion;
	}

	public Long getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Long usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Set getTemas() {
		return temas;
	}

	public void setTemas(Set temas) {
		this.temas = temas;
	}


}
