/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;

public class Tipo extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getNormativas() {
        return normativas;
    }

    public void setNormativas(Set normativas) {
        this.normativas = normativas;
    }

    private Long id;
    private Set normativas;
}
