/* Generated by Together */

package org.ibit.rol.sac.model;

import java.util.Set;

public class Tipo extends Traducible {

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set getNormativas() {
        return normativas;
    }

    public void setNormativas(Set normativas) {
        this.normativas = normativas;
    }

    /**
     * @return the tipoSia
     */
    public Long getTipoSia() {
    	return tipoSia;
    }
    
    /**
     * @param tipoSia the tipoSia to set
     */
    public void setTipoSia(Long tipoSia) {
    	this.tipoSia = tipoSia;
    }
    

	/**
	 * @return the idBoib
	 */
	public Long getIdBoib() {
		return idBoib;
	}

	/**
	 * @param idBoib the idBoib to set
	 */
	public void setIdBoib(Long idBoib) {
		this.idBoib = idBoib;
	}


	private Long id;
    private Long tipoSia;
	private Set normativas;
	private Long idBoib;
}
