/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionEdificio implements Traduccion {

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    private String descripcion;
}
