/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionNormativa implements Traduccion {

    public String getSeccion() {
        return seccion;
    }

    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }

    public String getApartado() {
        return apartado;
    }

    public void setApartado(String apartado) {
        this.apartado = apartado;
    }

    public Integer getPaginaInicial() {
        return paginaInicial;
    }

    public void setPaginaInicial(Integer paginaInicial) {
        this.paginaInicial = paginaInicial;
    }

    public Integer getPaginaFinal() {
        return paginaFinal;
    }

    public void setPaginaFinal(Integer paginaFinal) {
        this.paginaFinal = paginaFinal;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getEnlace() {
        return enlace;
    }

    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    private String seccion;
    private String apartado;
    private Integer paginaInicial;
    private Integer paginaFinal;
    private String titulo;
    private String enlace;
    private Archivo archivo;
    private String observaciones;
    
    public TraduccionNormativa() {}
    
    public TraduccionNormativa(String titulo, String enlace, String apartado, Integer paginaInicial, Integer paginaFinal, String observaciones) {
    	this.titulo = titulo;
    	this.enlace = enlace;
    	this.apartado = apartado;
    	this.paginaInicial = paginaInicial;
    	this.paginaFinal = paginaFinal;
    	this.observaciones = observaciones;
    }
}
