/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionTipo implements Traduccion {

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    private String nombre;
}
