/* Generated by Together */

package org.ibit.rol.sac.model;

@Deprecated
public class TraduccionDocumentTramit extends TraduccionElementOrdenat {

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    private Archivo archivo;
}
