/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionNormativaExterna extends TraduccionNormativa {

    public String getResponsable() {
        return responsable;
    }

    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    private String responsable;
}
