/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionGrupoSuscripcion implements Traduccion {


    private String nombre;

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
