/* Generated by Together */

package org.ibit.rol.sac.model;

public interface TraduccionProcedimiento extends Traduccion {

    String getNombre();

    void setNombre(String nombre);

    String getResumen();

    void setResumen(String resumen);

    String getDestinatarios();

    void setDestinatarios(String destinatarios);

    String getRequisitos();

    void setRequisitos(String requisitos);

    String getPlazos();

    void setPlazos(String plazos);

    String getResolucion();

    void setResolucion(String resolucion);

    String getNotificacion();

    void setNotificacion(String notificacion);

    String getRecursos();

    void setRecursos(String recursos);

    String getObservaciones();

    void setObservaciones(String observaciones);

    String getLugar();

    void setLugar(String lugar);

    String getResultat();

	void setResultat(String resultat);

}
