/* Generated by Together */

package org.ibit.rol.sac.model;

public class TraduccionProcedimientoLocal implements TraduccionProcedimiento {

	private static final long serialVersionUID = -1313486359929062988L;

	private String nombre;
	private String resumen;
	private String destinatarios;
	private String resultat;
	@Deprecated
	private String requisitos;
	@Deprecated
	private String plazos;
	private String resolucion;
	private String notificacion;
	private String recursos;
	private String observaciones;
	@Deprecated
	private String lugar;

	/** LOPD **/
	private String lopdFinalidad;
	private String lopdDestinatario;
	private String lopdDerechos;
	private Archivo lopdInfoAdicional;

	@Override
	public String getNombre() {
		return nombre;
	}

	@Override
	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

	@Override
	public String getResumen() {
		return resumen;
	}

	@Override
	public void setResumen(final String resumen) {
		this.resumen = resumen;
	}

	@Override
	public String getDestinatarios() {
		return destinatarios;
	}

	@Override
	public void setDestinatarios(final String destinatarios) {
		this.destinatarios = destinatarios;
	}

	@Override
	@Deprecated
	public String getRequisitos() {
		return requisitos;
	}

	@Override
	@Deprecated
	public void setRequisitos(final String requisitos) {
		this.requisitos = requisitos;
	}

	@Override
	@Deprecated
	public String getPlazos() {
		return plazos;
	}

	@Override
	@Deprecated
	public void setPlazos(final String plazos) {
		this.plazos = plazos;
	}

	@Override
	public String getResolucion() {
		return resolucion;
	}

	@Override
	public void setResolucion(final String resolucion) {
		this.resolucion = resolucion;
	}

	@Override
	public String getNotificacion() {
		return notificacion;
	}

	@Override
	public void setNotificacion(final String notificacion) {
		this.notificacion = notificacion;
	}

	@Override
	public String getRecursos() {
		return recursos;
	}

	@Override
	public void setRecursos(final String recursos) {
		this.recursos = recursos;
	}

	@Override
	public String getObservaciones() {
		return observaciones;
	}

	@Override
	public void setObservaciones(final String observaciones) {
		this.observaciones = observaciones;
	}

	@Override
	@Deprecated
	public String getLugar() {
		return lugar;
	}

	@Override
	@Deprecated
	public void setLugar(final String lugar) {
		this.lugar = lugar;
	}

	@Override
	public String getResultat() {
		return resultat;
	}

	@Override
	public void setResultat(final String resultat) {
		this.resultat = resultat;
	}

	/**
	 * @return the lopdFinalidad
	 */
	public String getLopdFinalidad() {
		return lopdFinalidad;
	}

	/**
	 * @param lopdFinalidad
	 *            the lopdFinalidad to set
	 */
	public void setLopdFinalidad(final String lopdFinalidad) {
		this.lopdFinalidad = lopdFinalidad;
	}

	/**
	 * @return the lopdDestinatario
	 */
	public String getLopdDestinatario() {
		return lopdDestinatario;
	}

	/**
	 * @param lopdDestinatario
	 *            the lopdDestinatario to set
	 */
	public void setLopdDestinatario(final String lopdDestinatario) {
		this.lopdDestinatario = lopdDestinatario;
	}

	/**
	 * @return the lopdDerechos
	 */
	public String getLopdDerechos() {
		return lopdDerechos;
	}

	/**
	 * @param lopdDerechos
	 *            the lopdDerechos to set
	 */
	public void setLopdDerechos(final String lopdDerechos) {
		this.lopdDerechos = lopdDerechos;
	}

	/**
	 * @return the lopdInfoAdicional
	 */
	public Archivo getLopdInfoAdicional() {
		return lopdInfoAdicional;
	}

	/**
	 * @param lopdInfoAdicional the lopdInfoAdicional to set
	 */
	public void setLopdInfoAdicional(Archivo lopdInfoAdicional) {
		this.lopdInfoAdicional = lopdInfoAdicional;
	}

	@Override
	public String toString() {
		return "TraduccionProcedimientoLocal [destinatarios=" + destinatarios + ", lugar=" + lugar + ", nombre="
				+ nombre + ", notificacion=" + notificacion + ", observaciones=" + observaciones + ", plazos=" + plazos
				+ ", recursos=" + recursos + ", requisitos=" + requisitos + ", resolucion=" + resolucion + "]";
	}

}
