/* Generated by Together */

package org.ibit.rol.sac.model;

/**
 *
 */
public class TraduccionDocumentoResumen implements Traduccion {

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public ArchivoResumen getArchivoResumen() {
        return archivoResumen;
    }
    
    public void setArchivoResumen(ArchivoResumen archivoResumen) {
		this.archivoResumen = archivoResumen;
	}

    private String titulo;
    private String descripcion;
    private ArchivoResumen archivoResumen;
	
}
