/* Generated by Together */

package org.ibit.rol.sac.model;

public class TraduccionFicha implements Traduccion {

	public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescAbr() {
        return descAbr;
    }

    public void setDescAbr(String descAbr) {
        this.descAbr = descAbr;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    
    private String titulo;
    private String descAbr;
    private String descripcion;
    private String url;

}
