/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionSeccion implements Traduccion {

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

    private String nombre;
    // atributo privado introducido para poder añadir un
    //texto descriptivo (opcional) en todas las secciones.
    private String descripcion;
    

}
