/* Generated by Together */

package org.ibit.rol.sac.model;


public class TraduccionTramite implements Traduccion {

	private String nombre;
    //#351 se cambia descripcion por observaciones (como ya existia observaciones, solo hay que comentar)
    //private String descripcion;
    private String documentacion;
    private String requisits;
    private String plazos;
    private String observaciones;
    private String lugar;
    private String urlTramiteExterno;
	
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDocumentacion() {
        return documentacion;
    }

    public void setDocumentacion(String documentacion) {
        this.documentacion = documentacion;
    }

    public String getPlazos() {
        return plazos;
    }

    public void setPlazos(String plazos) {
        this.plazos = plazos;
    }

    public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getLugar() {
		return lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getRequisits() {
		return requisits;
	}

	public void setRequisits(String requisits) {
		this.requisits = requisits;
	}

	@Override
	public String toString() {
		return "TraduccionTramite [observaciones=" + observaciones
				+ ", documentacion=" + documentacion + ", nombre=" + nombre
				+ ", observaciones=" + observaciones + ", plazos=" + plazos
				+ ", urlTramiteExterno=" + urlTramiteExterno 
				+ "]";
	}

	public String getUrlTramiteExterno() {
		return urlTramiteExterno;
	}

	public void setUrlTramiteExterno(String urlTramiteExterno) {
		this.urlTramiteExterno = urlTramiteExterno;
	}

	

}
