/* Generated by Together */

package org.ibit.rol.sac.model;

public class TraduccionFicha implements Traduccion {

	public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescAbr() {
        return descAbr;
    }

    public void setDescAbr(String descAbr) {
        this.descAbr = descAbr;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    
    public String getUrlForo() {
        return urlForo;
    }

    public void setUrlForo(String urlForo) {
        this.urlForo = urlForo;
    } 
    
    public String getUrlVideo() {
        return urlVideo;
    }

    public void setUrlVideo(String urlVideo) {
        this.urlVideo = urlVideo;
    }    
    
    public Archivo getIcono() {
        return icono;
    }

    public void setIcono(Archivo icono) {
        this.icono = icono;
    }

    public Archivo getImagen() {
        return imagen;
    }

    public void setImagen(Archivo imagen) {
        this.imagen = imagen;
    }

    public Archivo getBaner() {
        return baner;
    }

    public void setBaner(Archivo baner) {
        this.baner = baner;
    }

    
    private String titulo;
    private String descAbr;
    private String descripcion;
    private String url;
    private String urlForo;
    private String urlVideo;
    private Archivo icono;
	private Archivo imagen;
	private Archivo baner;
}
