/* Generated by Together */

package org.ibit.rol.sac.model;

public class TraduccionProcedimientoLocal implements TraduccionProcedimiento {

	private static final long serialVersionUID = -1313486359929062988L;
	
	private String nombre;
    private String resumen;
    private String destinatarios;
    private String resultat;
    @Deprecated
    private String requisitos;
    @Deprecated
    private String plazos;
    private String resolucion;
    private String notificacion;
    //private String silencio;
    private String recursos;
    private String observaciones;
    @Deprecated
    private String lugar;

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    public String getDestinatarios() {
        return destinatarios;
    }

    public void setDestinatarios(String destinatarios) {
        this.destinatarios = destinatarios;
    }

    @Deprecated
    public String getRequisitos() {
        return requisitos;
    }

    @Deprecated
    public void setRequisitos(String requisitos) {
        this.requisitos = requisitos;
    }

    @Deprecated
    public String getPlazos() {
        return plazos;
    }
    @Deprecated
    public void setPlazos(String plazos) {
        this.plazos = plazos;
    }
    public String getResolucion() {
		return resolucion;
	}
	public void setResolucion(String resolucion) {
		this.resolucion = resolucion;
	}
	public String getNotificacion() {
		return notificacion;
	}
	public void setNotificacion(String notificacion) {
		this.notificacion = notificacion;
	}
//    public String getSilencio() {
//        return silencio;
//    }
//
//    public void setSilencio(String silencio) {
//        this.silencio = silencio;
//    }

    public String getRecursos() {
        return recursos;
    }

    public void setRecursos(String recursos) {
        this.recursos = recursos;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Deprecated
    public String getLugar() {
        return lugar;
    }

    @Deprecated
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

	public String getResultat() {
		return resultat;
	}

	public void setResultat(String resultat) {
		this.resultat = resultat;
	}

	@Override
	public String toString() {
		return "TraduccionProcedimientoLocal [destinatarios=" + destinatarios
				+ ", lugar=" + lugar + ", nombre=" + nombre + ", notificacion="
				+ notificacion + ", observaciones=" + observaciones
				+ ", plazos=" + plazos + ", recursos=" + recursos
				+ ", requisitos=" + requisitos + ", resolucion=" + resolucion
				//+ ", resumen=" + resumen + ", silencio=" + silencio 
				+ "]";
	}

    
    
}
