/* Generated by Together */

package org.ibit.rol.sac.model;

public class ValidacionNormativa {

    public final static Integer VIGENTE = 1;
    public final static Integer DEROGADA = 2;
    
}
