/* Generated by Together */

package org.ibit.rol.sac.model;

public class Validacion {

    public final static Integer PUBLICA = 1;
    public final static Integer INTERNA = 2;
    public final static Integer RESERVA = 3;
    public final static Integer BAJA = 4;
    
}
