/* Generated by Together */

package org.ibit.rol.sac.model;

import java.io.Serializable;

/**
 * Un ValueObject representa el modelo Java de un formulario struts.
 * @author u92770
 *
 */

public interface ValueObject extends Serializable {

}
