ALTER TABLE RSC_PROCED ADD PRO_FUNHAB BOOL DEFAULT FALSE;
ALTER TABLE RSC_PROCED ADD PRO_APOHAB BOOL DEFAULT FALSE;

COMMENT ON COLUMN RSC_PROCED.PRO_FUNHAB IS 'CAMPO SIA Disponible Funcionario Habilitado';
COMMENT ON COLUMN RSC_PROCED.PRO_APOHAB IS 'CAMPO SIA Disponible Apoderado Habilitado';