CREATE TABLE RSC_SIAUA (
    SUA_CODI     NUMBER(19,0),
    SUA_CODUNA NUMBER(19,0),
    SUA_USUARI VARCHAR2(200 CHAR),
    SUA_CONTRA VARCHAR2(200 CHAR),
    CONSTRAINT RSC_SUA_PK PRIMARY KEY (SUA_CODI),
    CONSTRAINT RSC_SUAUNA_FK FOREIGN KEY (SUA_CODUNA) REFERENCES RSC_UNIADM (UNA_CODI) ENABLE    
);
