SET SERVEROUTPUT ON;
--SCRIPT PARA INTRODUCIR LOS 3 NUEVOS TIPOS DE SIA.
DECLARE
  vIdTipo NUMBER;
BEGIN
  SELECT RSC_SEQ_ALL.nextval INTO vIdTipo FROM DUAL;
  INSERT INTO RSC_TIPO (TIP_CODI,TIP_CODSIA,TIP_IDBOIB) VALUES (vIdTipo, null, null);
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'ca', 'Directiva Europea'); 
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'es', 'Directiva Europea');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'en', 'European Directive');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'fr', 'Directive Européenne');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'de', 'Europäische Richtlinie');
  
  SELECT RSC_SEQ_ALL.nextval INTO vIdTipo FROM DUAL;
  INSERT INTO RSC_TIPO (TIP_CODI,TIP_CODSIA,TIP_IDBOIB) VALUES (vIdTipo, null, null);
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'ca', 'Llei Orgànica'); 
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'es', 'Ley Orgánica');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'en', 'Organic Law');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'fr', 'Loi Organique');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'de', 'Organisches Recht');
  
  SELECT RSC_SEQ_ALL.nextval INTO vIdTipo FROM DUAL;
  INSERT INTO RSC_TIPO (TIP_CODI,TIP_CODSIA,TIP_IDBOIB) VALUES (vIdTipo, null, null);
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'ca', 'Reglament Europeu'); 
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'es', 'Reglamento Europeo');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'en', 'European Regulation');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'fr', 'Réglementation européenne');
  INSERT INTO RSC_TRATIP (TTI_CODTIP, TTI_CODIDI, TTI_NOMBRE) VALUES (vIdTipo, 'de', 'Europäische Regelung');
  
  COMMIT;
  

END;
