--Tabla de relacion de documentos con normativa y su traducción.
CREATE TABLE RSC_DOCNOR
(
  DNO_CODI   NUMBER(19,0) NOT NULL ENABLE,
  DNO_CODNOR NUMBER(19,0) NOT NULL ENABLE,
  ORDEN  NUMBER(19,0) NOT NULL ENABLE,
  PRIMARY KEY (DNO_CODI),
  CONSTRAINT RSC_DOCNOR_ORDEN_UNIQUE UNIQUE (DNO_CODNOR, DNO_ORDEN) ENABLE,
  CONSTRAINT RSC_DOCNOR_NORMAT_FK FOREIGN KEY (DNO_CODNOR) REFERENCES RSC_NORMAT (NOR_CODI) ENABLE
);
COMMENT ON TABLE RSC_DOCNOR IS 'Documento asociado a una normativa';
COMMENT ON COLUMN RSC_DOCNOR.DNO_CODI is 'Identificador del documento';
COMMENT ON COLUMN RSC_DOCNOR.DNO_CODNOR is 'Identificador de la normativa';
COMMENT ON COLUMN RSC_DOCNOR.DNO_ORDEN is 'Orden del documento';

CREATE TABLE RSC_TRADNR
(
    TDN_CODDNR NUMBER(19,0) NOT NULL ENABLE,
    TDN_TITULO VARCHAR2(512 CHAR),
    TDN_ENLACE VARCHAR2(512 CHAR),
    TDN_DESCRI VARCHAR2(4000 CHAR),
    TDN_CODARC NUMBER(19,0),
    TDN_CODIDI VARCHAR2(2 BYTE) NOT NULL ENABLE,
    PRIMARY KEY (TDN_CODDNR, TDN_CODIDI),
    CONSTRAINT RSC_TRADNR_ARCHIV_FK FOREIGN KEY (TDN_CODARC) REFERENCES RSC_ARCHIV (ARC_CODI) ENABLE,
    CONSTRAINT RSC_TRADNR_DOCNOR_FK FOREIGN KEY (TDN_CODDNR) REFERENCES RSC_DOCNOR (DNO_CODI) ENABLE
);

COMMENT ON TABLE RSC_TRADNR IS 'Traducción del documento asociado a una normativa';
COMMENT ON COLUMN RSC_TRADNR.TDN_CODDNR is 'Identificador de la normativa. PK - 1';
COMMENT ON COLUMN RSC_TRADNR.TDN_CODIDI is 'Identificador del idioma (es / ca). PK - 2';
COMMENT ON COLUMN RSC_TRADNR.TDN_TITULO is 'Titulo del documento para mostrar en el modulo.';
COMMENT ON COLUMN RSC_TRADNR.TDN_CODARC is 'Identificador del archivo.';
COMMENT ON COLUMN RSC_TRADNR.TDN_ENLACE is 'Texto con el enlace URL.';

--Tabla de relacion con las unidad administrativas y normativas.
CREATE TABLE RSC_UNANOR
(
  UNN_CODNOR NUMBER(19,0) NOT NULL ENABLE,
  UNN_CODUNA NUMBER(19,0) NOT NULL ENABLE,
  UNN_CODI   NUMBER(19,0) NOT NULL ENABLE,
  CONSTRAINT RSC_UNN_PK PRIMARY KEY (UNN_CODI),
  CONSTRAINT RSC_UNNUNA_FK FOREIGN KEY (UNN_CODUNA) REFERENCES RSC_UNIADM (UNA_CODI) ENABLE,
  CONSTRAINT RSC_UNNNOR_FK FOREIGN KEY (UNN_CODNOR) REFERENCES RSC_NORMAT (NOR_CODI) ENABLE,
  UNIQUE (UNN_CODNOR, UNN_CODUNA)
);
COMMENT ON TABLE RSC_UNANOR IS 'Tabla que relaciona las UAs y las normativas';
COMMENT ON COLUMN RSC_UNANOR.UNN_CODNOR is 'Identificador de la normativa.';
COMMENT ON COLUMN RSC_UNANOR.UNN_CODI is 'Identificador de la tabla que relaciona normativas y UAs.';
COMMENT ON COLUMN RSC_UNANOR.UNN_CODUNA is 'Identificador de la UA.';


--Cambios en las normativas. 
ALTER TABLE RSC_NORMAT ADD NOR_TYPEN	VARCHAR2(64 CHAR); --Nuevo tipo que es normativa o normativaExterna
ALTER TABLE RSC_NORMAT ADD NOR_VALIDN	NUMBER(10, 0); --Nuevo valida
ALTER TABLE RSC_NORMAT ADD NOR_CODBOL_ANT	NUMBER(19, 0); --Codigo boletín antiguo
ALTER TABLE RSC_NORMAT ADD NOR_NUMNOR VARCHAR2(8 CHAR); --Numero normativa.
ALTER TABLE RSC_NORMAT MODIFY (NOR_TYPE NULL); --Ahora el tipo puede ser nulo
ALTER TABLE RSC_NORMAT MODIFY (NOR_TYPEN NOT NULL); --Ahora el tipon ya no es nulo
COMMENT ON COLUMN RSC_NORMAT.NOR_NUMNOR is 'Numero de la normativa.';
COMMENT ON COLUMN RSC_NORMAT.NOR_TYPEN is 'Nuevo tipo de la normativa.';
COMMENT ON COLUMN RSC_NORMAT.NOR_VALIDN is 'Nuevo valida de la normativa.';
COMMENT ON COLUMN RSC_NORMAT.NOR_CODBON is 'Nuevo codigo boletin de la normativa.';

	--La constraint obliga a que el numero de normativa siga el formato NNN/YYYY siendo N el nº y Y el año.
ALTER TABLE RSC_NORMAT
  ADD CONSTRAINT  RSC_NORMAT_NUMNOR_CHECK
  CHECK (REGEXP_LIKE(NOR_NUMNOR,'[[:digit:]]{0,3}/[[:digit:]]{4}')); 
  
--Renombra la vista de traduccion de normativas.  
RENAME RSC_TRANOR to RSC_TRANOR_VIEW;

--Crea ña tabla de traduccion de normativas.
CREATE TABLE RSC_TRANOR
  (
    TNR_CODNOR NUMBER(19,0) NOT NULL ENABLE,
    TNR_SECCIO VARCHAR2(256 CHAR),
    TNR_APARTA VARCHAR2(256 CHAR),
    TNR_PAGINI NUMBER(10,0),
    TNR_PAGFIN NUMBER(10,0),
    TNR_TITULO VARCHAR2(1024 CHAR),
    TNR_ENLACE VARCHAR2(512 CHAR),
    TNR_CODARC NUMBER(19,0),
    TNR_OBSERV VARCHAR2(4000 CHAR),
    TNR_CODIDI VARCHAR2(2 CHAR) NOT NULL ENABLE,
    CONSTRAINT RSC_TNR_PK PRIMARY KEY (TNR_CODNOR, TNR_CODIDI) ENABLE,
    CONSTRAINT RSC_TNRNOR_FK FOREIGN KEY (TNR_CODNOR) REFERENCES RSC_NORMAT (NOR_CODI) ENABLE,
    CONSTRAINT RSC_TNRARC_FK FOREIGN KEY (TNR_CODARC) REFERENCES RSC_ARCHIV (ARC_CODI) ENABLE
  );