<wsdl:definitions
	targetNamespace="http://ws.idioma.v2.api.rolsac.caib.es"
	xmlns:apachesoap="http://xml.apache.org/xml-soap" 
	xmlns:impl="http://ws.idioma.v2.api.rolsac.caib.es"
	xmlns:intf="http://ws.idioma.v2.api.rolsac.caib.es"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tns1="http://idioma.v2.api.rolsac.caib.es"
	xmlns:tns2="http://general.v2.api.rolsac.caib.es"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<wsdl:import namespace="urn:tns1" location="IdiomaCriteria.wsdl"/>
	<wsdl:import namespace="urn:tns2" location="BasicCriteria.wsdl"/>
	
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://ws.idioma.v2.api.rolsac.caib.es">
			<import namespace="http://xml.apache.org/xml-soap" />
			<import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
			<complexType name="ArrayOf_xsd_anyType">
				<complexContent>
					<restriction base="soapenc:Array">
						<attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:anyType[]" />
					</restriction>
				</complexContent>
			</complexType>
		</schema>
	</wsdl:types>
	
	<wsdl:message name="llistarIdiomesRequest">
		<wsdl:part name="in0" type="tns1:IdiomaCriteria" />
	</wsdl:message>
	<wsdl:message name="llistarIdiomesResponse">
		<wsdl:part name="llistarIdiomesReturn" type="impl:ArrayOf_xsd_anyType" />
	</wsdl:message>

	<wsdl:portType name="IdiomaQueryServiceEJBRemote">
		<wsdl:operation name="llistarIdiomes" parameterOrder="in0">
			<wsdl:input message="impl:llistarIdiomesRequest" name="llistarIdiomesRequest" />
			<wsdl:output message="impl:llistarIdiomesResponse" name="llistarIdiomesResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="IdiomaWSSoapBinding" type="impl:IdiomaQueryServiceEJBRemote">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="llistarIdiomes">
			<wsdlsoap:operation soapAction="" />
			<wsdl:input name="llistarIdiomesRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://intf.ejb.idioma.v2.api.rolsac.caib.es" use="encoded" />
			</wsdl:input>
			<wsdl:output name="llistarIdiomesResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://ws.idioma.v2.api.rolsac.caib.es"
					use="encoded" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="IdiomaQueryServiceEJBRemoteService">
		<wsdl:port binding="impl:IdiomaWSSoapBinding" name="IdiomaWS">
			<wsdlsoap:address location="https://localhost:8443/sacws-api/services/IdiomaWS" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>