CREATE TABLE RSC_TRAMPL(
	"TPA_CODI"  NUMBER(19,0),
	"TPA_IDENTI" VARCHAR2(256 CHAR) NOT NULL,
	"TPA_VERSION" VARCHAR2(3 CHAR) NOT NULL,
	"TPA_PARAMS" VARCHAR2(1000 CHAR)  NOT NULL,
	"TPA_CODPLT"  NUMBER(19,0) NOT NULL,
	"TPA_FASE" NUMBER(2,0) DEFAULT 1,
 	CONSTRAINT RSC_TRAMPL_PK PRIMARY KEY (TPA_CODI),
  	CONSTRAINT RSC_TPAPLT_FK
    	FOREIGN KEY (TPA_CODPLT)
    	REFERENCES RSC_PLATAF (PLT_CODI)
);
/*
alter table RSC_TRAMPL add TPA_FASE NUMBER(2,0) DEFAULT 1;
UPDATE RSC_TRAMPL SET TPA_FASE = 1;
COMMIT;
alter table RSC_TRAMPL MODIFY TPA_FASE NOT NULL;
 */

COMMENT ON TABLE RSC_TRAMPL IS 'Tabla de plantilla de tramites';
COMMENT ON COLUMN RSC_TRAMPL.TPA_CODI IS 'PK de la plantilla';
COMMENT ON COLUMN RSC_TRAMPL.TPA_IDENTI IS 'Identificador del tramite de la plantilla';
COMMENT ON COLUMN RSC_TRAMPL.TPA_VERSION IS 'Version del tramite de la plantilla';
COMMENT ON COLUMN RSC_TRAMPL.TPA_PARAMS IS 'Params de la plantilla';
COMMENT ON COLUMN RSC_TRAMPL.TPA_CODPLT IS 'Codigo de la plataforma';
COMMENT ON COLUMN RSC_TRAMPL.TPA_FASE IS 'Fase';

CREATE TABLE  RSC_TRATPA
  (
    "TTP_CODPLT" NUMBER(19,0) NOT NULL ENABLE,
    "TTP_CODIDI" VARCHAR2(2 CHAR) NOT NULL ENABLE,
    "TTP_NOMBRE" VARCHAR2(256 CHAR),
    CONSTRAINT "RSC_TTP_PK" PRIMARY KEY ("TTP_CODPLT", "TTP_CODIDI"),
    CONSTRAINT "RSC_TRATTP_FK" FOREIGN KEY ("TTP_CODPLT") REFERENCES "RSC_TRAMPL" ("TPA_CODI") ENABLE
  );


COMMENT ON TABLE RSC_TRATPA IS 'Traduccion de plantilla de tramites';
COMMENT ON COLUMN RSC_TRATPA.TTP_CODPLT IS 'PK de la traduccion plantilla';
COMMENT ON COLUMN RSC_TRATPA.TTP_CODIDI IS 'Idioma de la traduccion plantilla';
COMMENT ON COLUMN RSC_TRATPA.TTP_NOMBRE IS 'Nombre de la traduccion plantilla';

/** Anyadido en el tramite **/
ALTER TABLE RSC_TRAMIT ADD "TRA_CODPLN" NUMBER(19,0) NULL;
ALTER TABLE RSC_TRAMIT ADD CONSTRAINT RSC_TRAMPLN_FK
    	FOREIGN KEY (TRA_CODPLN)
    	REFERENCES RSC_TRAMPL (TPA_CODI);




/** grants hacia www_rolsac
GRANT all on RSC_TRATPA to www_rolsac;
GRANT all on RSC_TRAMPL to www_rolsac;
**/

/** en el usuario www_rolsac ejecutar
create synonym RSC_TRATPA for rolsac.RSC_TRATPA;
create synonym RSC_TRAMPL for rolsac.RSC_TRAMPL;
*/

alter table RSC_TRAMPL MODIFY TPA_FASE NOT NULL;