-- Indicador para público objetivo .
ALTER TABLE RSC_PUBOBJ ADD POB_INTERNO bool DEFAULT FALSE;
COMMENT ON COLUMN RSC_PUBOBJ.POB_INTERNO is 'Indica si el publico objetivo es interno.';

--Indica si un procedimiento/servicio es comun
ALTER TABLE RSC_SERVIC ADD SER_COMUN BOOL DEFAULT FALSE;
ALTER TABLE RSC_PROCED ADD PRO_COMUN BOOL DEFAULT FALSE;

--Anyade la plataforma de tramitacion
CREATE TABLE RSC_PLATAF
  (
   PLT_CODI int8 not null,
   PLT_NOMBRE varchar(128),
   PLT_ORDEN int4 not null,
   primary key (PLT_CODI)
  );

COMMENT ON TABLE RSC_PLATAF IS 'Tabla de plataformas de tramitacion';
COMMENT ON COLUMN RSC_PLATAF.PLT_CODI IS 'PK de la plataforma';
COMMENT ON COLUMN RSC_PLATAF.PLT_NOMBRE IS 'Nombre de la plataforma';

CREATE TABLE  RSC_TRAPLT
  (
   TPT_CODPLT int8 not null,
   TPT_DESCRI varchar(1000),
   TPT_URL varchar(1000),
   TPT_CODIDI varchar(2) not null,
   primary key (TPT_CODPLT, TPT_CODIDI)
  );

COMMENT ON TABLE RSC_TRAPLT IS 'Tabla de traduccion plataformas de tramitacion';
COMMENT ON COLUMN RSC_TRAPLT.TPT_CODPLT IS 'PK de la plataforma';
COMMENT ON COLUMN RSC_TRAPLT.TPT_CODIDI IS 'Idioma';
COMMENT ON COLUMN RSC_TRAPLT.TPT_DESCRI IS 'Descripcion de la plataforma';
COMMENT ON COLUMN RSC_TRAPLT.TPT_URL IS 'Url de la plataforma';

--- Anayadido la info para tramite
ALTER TABLE RSC_TRAMIT ADD TRA_CODPLT	INT8;
ALTER TABLE RSC_TRAMIT ADD TRA_PARAMS VARCHAR(255 );
COMMENT ON COLUMN RSC_TRAMIT.TRA_CODPLT IS 'FK a plataforma de tramitacion';
COMMENT ON COLUMN RSC_TRAMIT.TRA_PARAMS IS 'Parametros en caso de ser un tramite';
ALTER TABLE RSC_TRAMIT ADD CONSTRAINT "RSC_TRAMPLT_FK" FOREIGN KEY (TRA_CODPLT) REFERENCES RSC_PLATAF (PLT_CODI);

ALTER TABLE RSC_SERVIC ADD SER_CODPLT	INT8;
ALTER TABLE RSC_SERVIC ADD SER_PARAMS VARCHAR(255);
COMMENT ON COLUMN RSC_SERVIC.SER_CODPLT IS 'FK a plataforma de tramitacion';
COMMENT ON COLUMN RSC_SERVIC.SER_PARAMS IS 'Parametros en caso de ser telematico';
ALTER TABLE RSC_SERVIC ADD CONSTRAINT RSC_SERPLT_FK FOREIGN KEY (SER_CODPLT) REFERENCES RSC_PLATAF (PLT_CODI);