<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="http://agrupacioMateria.v2.api.rolsac.caib.es"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    name="AgrupacioMateriaOrdenacio"
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns2="http://general.v2.api.rolsac.caib.es"
    targetNamespace="http://ws.agrupacioMateria.v2.api.rolsac.caib.es">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://agrupacioMateria.v2.api.rolsac.caib.es">
        <import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
        <import namespace="http://general.v2.api.rolsac.caib.es" />

        <simpleType name="AgrupacioMateriaOrdenacio">
            <restriction base="xsd:string">
                <enumeration value="id_asc" />
                <enumeration value="id_desc" />
                <enumeration value="codigoEstandar_asc" />
                <enumeration value="codigoEstandar_desc" />
                <enumeration value="seccion_asc" />
                <enumeration value="seccion_desc" />
            </restriction>
        </simpleType>

    </schema>
  </wsdl:types>
</wsdl:definitions>