<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="http://general.v2.api.rolsac.caib.es"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    name="BasicCriteria"
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://ws.general.v2.api.rolsac.caib.es">   
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://general.v2.api.rolsac.caib.es">
        <import namespace="http://xml.apache.org/xml-soap" />
        <import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
        <complexType abstract="true" name="BasicCriteria">
            <sequence>
                <element name="id" nillable="true" type="xsd:string" />
                <element name="idioma" nillable="true" type="xsd:string" />
                <element name="inici" nillable="true" type="xsd:string" />
                <element name="tamany" nillable="true" type="xsd:string" />
            </sequence>
        </complexType>
    </schema>
  </wsdl:types>
</wsdl:definitions>
