<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="http://procediment.v2.api.rolsac.caib.es"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    name="ProcedimentOrdenacio"
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns2="http://general.v2.api.rolsac.caib.es"
    targetNamespace="http://ws.procediment.v2.api.rolsac.caib.es">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://procediment.v2.api.rolsac.caib.es">
        <import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
        <import namespace="http://general.v2.api.rolsac.caib.es" />

        <simpleType name="ProcedimentOrdenacio">
            <restriction base="xsd:string">
                <enumeration value="id_asc" />
                <enumeration value="id_desc" />
                <enumeration value="signatura_asc" />
                <enumeration value="signatura_desc" />
                <enumeration value="fechaCaducidad_asc" />
                <enumeration value="fechaCaducidad_desc" />
                <enumeration value="fechaPublicacion_asc" />
                <enumeration value="fechaPublicacion_desc" />
                <enumeration value="fechaActualizacion_asc" />
                <enumeration value="fechaActualizacion_desc" />
                <enumeration value="version_asc" />
                <enumeration value="version_desc" />
                <enumeration value="familia_asc" />
                <enumeration value="familia_desc" />
            </restriction>
        </simpleType>

    </schema>
  </wsdl:types>
</wsdl:definitions>