-- TAULA RSC_SOLRPD
CREATE TABLE RSC_SOLRPD
  (
    SLP_ID   integer NOT NULL,
    SLP_TIPO character varying(128),
    SLP_IDELEM integer,
    SLP_ACCION integer,
    SLP_FECCRE date,
    SLP_FECIDX date,
    SLP_RESULT smallint,
    SLP_TXTERR character varying(4000)  
         
  );
  
  ALTER TABLE ONLY RSC_SOLRPD
    ADD CONSTRAINT RSC_SOLRPD_PK PRIMARY KEY (SLP_ID);

  COMMENT ON TABLE  RSC_SOLRPD IS 'Indexacion';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_ID       IS 'Identificador';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_TIPO     IS 'Tipo';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_IDELEM   IS 'Identificador Elemento';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_ACCION   IS 'Accion. 1 - Indexar, 2 - Borrar';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_FECCRE   IS 'Fecha Creacion';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_FECIDX   IS 'Fecha Ejecucion de indexacion';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_RESULT   IS 'Resultado.  0 - Pendiente, 1 Ejecutado correctamente, -1 Ejecutado con errores';
  COMMENT ON COLUMN RSC_SOLRPD.SLP_TXTERR   IS 'Mensaje de error que indique porque no se ha indexado';
  
  
---tabla solr job 
CREATE TABLE RSC_SOLJOB
  (
    JOB_ID NUMBER(19,0) NOT NULL ENABLE,
    JOB_FECINI DATE DEFAULT SYSDATE,
    JOB_FECFIN DATE,
    JOB_FECFCH DATE,
    JOB_FECPRO DATE,
    JOB_FECNOR DATE,
    JOB_FECTRA DATE,
    JOB_FECUNA DATE,
    JOB_TOTFCH NUMBER(5,2) DEFAULT 0,
    JOB_TOTDFC NUMBER(5,2) DEFAULT 0,
    JOB_TOTPRO NUMBER(5,2) DEFAULT 0,
    JOB_TOTDPR NUMBER(5,2) DEFAULT 0,
    JOB_TOTNOR NUMBER(5,2) DEFAULT 0,
    JOB_TOTDNO NUMBER(5,2) DEFAULT 0,
    JOB_TOTTRA NUMBER(5,2) DEFAULT 0,
    JOB_TOTUNA NUMBER(5,2) DEFAULT 0,
    CONSTRAINT RSC_JOB_PK PRIMARY KEY (JOB_ID) 
  );

 -- Comentarios de la tabla solr job
  COMMENT ON COLUMN RSC_SOLJOB.JOB_ID IS 'Identificador de la clase.';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECINI IS 'Fecha de inicio';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECFIN IS 'Fecha fin';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECFCH IS 'Fecha fin ejecutando fichas.';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECPRO IS 'Fecha fin ejecutando procedimientos.';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECNOR IS 'Fecha fin ejecutando normativas.';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECTRA IS 'Fecha fin ejecutando trámites.';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_FECUNA IS 'Fecha fin ejecutando unidad administrativa';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTFCH IS 'Porcentaje de total fichas';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTDFC IS 'Porcentaje de total fichas documento';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTPRO IS 'Porcentaje de total procedimiento';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTDPR IS 'Porcentaje de total procedimiento documento';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTNOR IS 'Porcentaje de total normativas';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTDNO IS 'Porcentaje de total normativas documento';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTTRA IS 'Porcentaje de total tramite';
  COMMENT ON COLUMN RSC_SOLJOB.JOB_TOTUNA IS 'Porcentaje de total Unid. Adminitr.';
  
   --AFEGIR CAMP PER CORRESPONDENCIA UAS DIR3-ROLSAC
ALTER TABLE RSC_UNIADM ADD UNA_CODDR3 VARCHAR2(12 CHAR);
COMMENT ON COLUMN RSC_UNIADM.UNA_CODDR3 IS 'CODI UNITAT ADMINISTRATIVA DIR3';  

 --AFEGIR TAULA TIPUS NORMATIVES SIA
CREATE TABLE RSC_SIATNR (
  SNR_CODTNR bigint,
  SNR_NOMBRE character varying(256)
);
ALTER TABLE RSC_SIATNR ADD (CONSTRAINT RSC_SIATNR_PK PRIMARY KEY (SNR_CODTNR));
COMMENT ON COLUMN RSC_SIATNR.SNR_CODTNR IS 'CODI TIPUS NORMA SIA';
COMMENT ON COLUMN RSC_SIATNR.SNR_NOMBRE IS 'NOM TIPUS NORMA SIA';

 --AFEGIR TAULA MATERIES SIA
CREATE TABLE RSC_SIAMAT (
  SMT_CODMAT bigint,
  SMT_NOMBRE character varying(256)
);
ALTER TABLE RSC_SIAMAT ADD (CONSTRAINT RSC_SIAMAT_PK PRIMARY KEY (SMT_CODMAT));
COMMENT ON COLUMN RSC_SIAMAT.SMT_CODMAT IS 'CODI MATERIA SIA';
COMMENT ON COLUMN RSC_SIAMAT.SMT_NOMBRE IS 'NOM MATERIA SIA';

 --AFEGIR CAMP PER CORRESPONDENCIA MATERIES SIA-ROLSAC
ALTER TABLE RSC_MATERI ADD (MAT_CODSIA NUMBER(19,0));
COMMENT ON COLUMN RSC_MATERI.MAT_CODSIA IS 'CODI MATERIA SIA';
ALTER TABLE RSC_MATERI ADD (CONSTRAINT RSC_MATSMT_FK  FOREIGN KEY (MAT_CODSIA) REFERENCES RSC_SIAMAT (SMT_CODMAT));

 --AFEGIR CAMP PER CORRESPONDENCIA TIPUS NORMATIVES SIA-ROLSAC
ALTER TABLE RSC_TIPO ADD (TIP_CODSIA NUMBER(19,0));
COMMENT ON COLUMN RSC_TIPO.TIP_CODSIA IS 'CODI TIPUS NORMA SIA';
ALTER TABLE RSC_TIPO ADD (CONSTRAINT RSC_TIPSNR_FK  FOREIGN KEY (TIP_CODSIA) REFERENCES RSC_SIATNR (SNR_CODTNR));

 --AFEGIR CAMP PER CORRESPONDENCIA UAS SIA-ROLSAC
ALTER TABLE RSC_PROCED ADD PRO_CODSIA VARCHAR2(12 CHAR);
COMMENT ON COLUMN RSC_PROCED.PRO_CODSIA IS 'CODI SIA';

 --Crear tabla silenci
CREATE TABLE RSC_SILADM (
  SIL_CODI integer NOT NULL ENABLE,
  primary key (SIL_CODI)
);
COMMENT ON COLUMN RSC_SILADM.SIL_CODI IS 'CODI SILENCI ADM';

create table RSC_TRASIL (
   TSI_CODSIL integer not null,
   TSI_NOMBRE character varying(256),
   TSI_DESCRI character varying(4000),
   TSI_CODIDI character varying(2) not null,
   primary key (TSI_CODSIL, TSI_CODIDI)
);
alter table RSC_TRASIL add constraint RSC_TSISIL_FK foreign key (TSI_CODSIL) references RSC_SILADM;

 --AFEGIR CAMP PER SILENCI
ALTER TABLE RSC_PROCED ADD PRO_CODSIL integer;
COMMENT ON COLUMN RSC_PROCED.PRO_CODSIL IS 'CODI SILENCI';
alter table RSC_PROCED add constraint RSC_PRO_CODSIL_SERV_FK foreign key (PRO_CODSIL) references RSC_SILADM;
  