UPDATE RSC_PROMSJ SET PMN_USUARIO = 'Desconocido' WHERE PMN_USUARIO IS NULL;
UPDATE RSC_SERMSJ SET SMN_USUARIO = 'Desconocido' WHERE SMN_USUARIO IS NULL;
COMMIT;
ALTER TABLE RSC_PROMSJ MODIFY PMN_USUARIO NOT NULL;
ALTER TABLE RSC_SERMSJ MODIFY SMN_USUARIO NOT NULL;