--24-06-10

alter table RSC_ADMREM add ADM_VERSIO NUMBER;
-- ja existeix

-- tabla RSC_ADMREM 
UPDATE RSC_ADMREM SET ADM_VERSIO=1 WHERE ADM_VERSIO is NULL;
-- ok

-- tabla RSC_TRAMIT 
--xx-07-10
ALTER TABLE RSC_TRAMIT ADD TRR_IDEXTE NUMBER(19,0) NULL;
-- ok
ALTER TABLE RSC_TRAMIT ADD TRR_URLREM VARCHAR2(512) NULL;
-- ok
ALTER TABLE RSC_TRAMIT ADD TRR_CODADM NUMBER(19,0) NULL;
-- ok
ALTER TABLE RSC_TRAMIT ADD TRA_TYPE VARCHAR2(64) NULL;
UPDATE RSC_TRAMIT SET TRA_TYPE='tramite' WHERE TRA_TYPE is NULL;
ALTER TABLE RSC_TRAMIT modify (TRA_TYPE  not null);
-- ok

alter table RSC_TRAMIT add constraint RSC_TRRADM_FK foreign key (TRR_CODADM) references RSC_ADMREM;
-- ok

-- tabla RSC_INICI 
alter table RSC_INICI add INI_CODEST VARCHAR2(256) NULL;
-- ok

--25-11-10 (hay que ejecutar estos scripts en ROLSACPMA(acordarse de cambiar el sufijo a PMA) y en ROLSAC
-- tabla RSC_NORMAT 
ALTER TABLE RSC_NORMAT ADD NER_IDEXTE NUMBER(19,0) NULL;
ALTER TABLE RSC_NORMAT ADD NER_URLREM VARCHAR2(512) NULL;
ALTER TABLE RSC_NORMAT ADD NER_CODADM NUMBER(19,0) NULL;
alter table RSC_NORMAT add constraint RSC_NERADM_FK foreign key (NER_CODADM) references RSC_ADMREM;

-- tabla RSC_DOCUME  
--18-01-11  Documento Remoto
ALTER TABLE RSC_DOCUME ADD DOR_IDEXTE NUMBER(19,0) NULL;
ALTER TABLE RSC_DOCUME ADD DOR_URLREM VARCHAR2(512) NULL;
ALTER TABLE RSC_DOCUME ADD DOR_CODADM NUMBER(19,0) NULL;

ALTER TABLE RSC_DOCUME add DOC_TYPE  varchar2(64) null;
UPDATE RSC_DOCUME SET DOC_TYPE='documento' WHERE DOC_TYPE is NULL;
ALTER TABLE RSC_DOCUME modify (DOC_TYPE  not null);
ALTER TABLE RSC_DOCUME add constraint RSC_DORADM_FK foreign key (DOR_CODADM) references RSC_ADMREM;


-- rename doc i taxa
alter table RSC_DOCUME drop constraint RSC_DOCARC_FK;
alter table RSC_DOCUME add  DOC_CODARC2 NUMBER(19,0);
update RSC_DOCUME set DOC_CODARC2 = DOC_CODARC;
alter table RSC_DOCUME drop column DOC_CODARC;
alter table RSC_DOCUME add constraint RSC_DOCARC2_FK foreign key (DOC_CODARC2) references RSC_ARCHIV;

-- tabla RSC_TAXA 
alter table RSC_TAXA drop constraint RSC_CODITRA_FK;
alter table RSC_TAXA add  TAX_CODTRA NUMBER(19,0);
update RSC_TAXA set TAX_CODTRA = CODITRA;
alter table RSC_TAXA drop column CODITRA;
alter table RSC_TAXA add constraint RSC_TAXTRA_FK foreign key (TAX_CODTRA) references RSC_TRAMIT;

