

--19-03-10

alter table RSC_TRASEC add TSE_DESCRI varchar2(4000);

--21-04-10

alter table RSC_COMENT add COM_SUBSAN  number(1,0);
alter table RSC_FICHA add FIC_RESPON VARCHAR2(256);
alter table RSC_ADMREM add ADM_RESPON VARCHAR2(256);
alter table RSC_PROCED add PRO_RESPON VARCHAR2(256);
alter table RSC_USUARI add USU_EMAIL VARCHAR2(256);
UPDATE RSC_COMENT SET COM_SUBSAN=0 WHERE COM_SUBSAN is NULL;

--18-06-10

alter table RSC_EDIFIC add EDR_IDEXTE  number(19,0);
alter table RSC_EDIFIC add EDR_CODADM  number(19,0);
alter table RSC_EDIFIC add EDI_TYPE  varchar2(64) not null;

alter table RSC_EDIFIC add constraint RSC_EDRADM_FK foreign key (EDR_CODADM) references RSC_ADMREM;
UPDATE RSC_EDIFIC SET EDI_TYPE='edificio' WHERE EDI_TYPE is NULL;

--24-06-10

alter table RSC_ADMREM add ADM_VERSIO NUMBER;
UPDATE RSC_ADMREM SET ADM_VERSIO=1 WHERE ADM_VERSIO is NULL;

--xx-07-10
ALTER TABLE RSC_TRAMIT ADD TRR_IDEXTE NUMBER(19,0) NULL;
ALTER TABLE RSC_TRAMIT ADD TRR_URLREM VARCHAR2(512) NULL;
ALTER TABLE RSC_TRAMIT ADD TRR_CODADM NUMBER(19,0) NULL;
ALTER TABLE RSC_TRAMIT ADD TRA_TYPE VARCHAR2(64) NOT NULL;

alter table RSC_TRAMIT add constraint RSC_TRRADM_FK foreign key (TRR_CODADM) references RSC_ADMREM;
UPDATE RSC_TRAMIT SET TRA_TYPE='tramite' WHERE TRA_TYPE is NULL;
 
alter table RSC_INICI add INI_CODEST VARCHAR2(256) NULL;


--25-11-10 (hay que ejecutar estos scripts en ROLSACPMA(acordarse de cambiar el sufijo a PMA) y en ROLSAC

ALTER TABLE RSC_NORMAT ADD NER_IDEXTE NUMBER(19,0) NULL;
ALTER TABLE RSC_NORMAT ADD NER_URLREM VARCHAR2(512) NULL;
ALTER TABLE RSC_NORMAT ADD NER_CODADM NUMBER(19,0) NULL;

alter table RSC_NORMAT add constraint RSC_NERADM_FK foreign key (NER_CODADM) references RSC_ADMREM;

--18-01-11  Documento Remoto
ALTER TABLE RSC_DOCUME ADD DOR_IDEXTE NUMBER(19,0) NULL;
ALTER TABLE RSC_DOCUME ADD DOR_URLREM VARCHAR2(512) NULL;
ALTER TABLE RSC_DOCUME ADD DOR_CODADM NUMBER(19,0) NULL;
alter table RSC_DOCUME add DOC_TYPE  varchar2(64) not null;

alter table RSC_DOCUME add constraint RSC_DORADM_FK foreign key (DOR_CODADM) references RSC_ADMREM;
UPDATE RSC_DOCUME SET DOC_TYPE='documento' WHERE DOC_TYPE is NULL;

