--Anyade la plataforma de tramitacion
create table RSC_LOPDLEG (
   LEG_CODI int8 not null,
   LEG_IDENTI varchar(255),
   LEG_DEFAULT bool,
   primary key (LEG_CODI)
);

COMMENT ON TABLE  RSC_LOPDLEG IS 'Tabla de lopd legitimacion';
COMMENT ON COLUMN RSC_LOPDLEG.LEG_CODI IS 'PK de la lopd legitimacion';
COMMENT ON COLUMN RSC_LOPDLEG.LEG_IDENTI IS 'Identificador del lopd legitimacion';
COMMENT ON COLUMN RSC_LOPDLEG.LEG_DEFAULT IS 'Indica el legitimacion por defecto';
  
create table RSC_TRALET (
   TLE_CODLEG int8 not null,
   TLE_NOMBRE varchar(1024),
   TLE_CODIDI varchar(2) not null,
   primary key (TLE_CODLEG, TLE_CODIDI)
);
alter table RSC_TRALET add constraint RSC_TRALET_FK foreign key (TLE_CODLEG) references RSC_LOPDLEG (LEG_CODI);
  

COMMENT ON TABLE  RSC_TRALET IS 'Tabla de traduccion plataformas de tramitacion';
COMMENT ON COLUMN RSC_TRALET.TLE_CODLEG IS 'PK de la legitimacion lopd';
COMMENT ON COLUMN RSC_TRALET.TLE_CODIDI IS 'Idioma';
COMMENT ON COLUMN RSC_TRALET.TLE_NOMBRE IS 'Nombre de la plataforma';

/**
PERFIL ROLSAC
GRANT SELECT,INSERT,UPDATE,DELETE ON RSC_LOPDLEG TO www_rolsac;
GRANT SELECT,INSERT,UPDATE,DELETE ON RSC_TRALET TO www_rolsac;

PERFIL WWW_ROLSAC
CREATE SYNONYM RSC_LOPDLEG FOR rolsac.RSC_LOPDLEG;
CREATE SYNONYM RSC_TRALET FOR rolsac.RSC_TRALET;

**/

/** Cambios en procs **/
ALTER TABLE RSC_PROCED ADD PRO_CODLEG int8;
ALTER TABLE RSC_PROCED ADD CONSTRAINT RSC_PRO_CODLEG_FK FOREIGN KEY (PRO_CODLEG) REFERENCES RSC_LOPDLEG (LEG_CODI) ;
COMMENT ON COLUMN RSC_PROCED.PRO_CODLEG IS 'Indica la legitimacion del procedimiento';

ALTER TABLE RSC_TRAPRO ADD TPR_LOPDFI text;
ALTER TABLE RSC_TRAPRO ADD TPR_LOPDDS text;
ALTER TABLE RSC_TRAPRO ADD TPR_LOPDDR text;
COMMENT ON COLUMN RSC_TRAPRO.TPR_LOPDFI IS 'Indica el lopd finalidad';
COMMENT ON COLUMN RSC_TRAPRO.TPR_LOPDDS IS 'Indica el lopd destinatario';
COMMENT ON COLUMN RSC_TRAPRO.TPR_LOPDDR IS 'Indica el lopd derechos';

/** Cambios en servs **/
ALTER TABLE RSC_SERVIC ADD SER_CODLEG int8;
ALTER TABLE RSC_SERVIC ADD CONSTRAINT RSC_SER_CODLEG_FK FOREIGN KEY (SER_CODLEG) REFERENCES RSC_LOPDLEG (LEG_CODI) ;
COMMENT ON COLUMN RSC_SERVIC.SER_CODLEG IS 'Indica la legitimacion del servicio';

ALTER TABLE RSC_TRASER ADD TSR_LOPDFI text;
ALTER TABLE RSC_TRASER ADD TSR_LOPDDS text;
ALTER TABLE RSC_TRASER ADD TSR_LOPDDR text;
COMMENT ON COLUMN RSC_TRASER.TSR_LOPDFI IS 'Indica el lopd finalidad';
COMMENT ON COLUMN RSC_TRASER.TSR_LOPDDS IS 'Indica el lopd destinatario';
COMMENT ON COLUMN RSC_TRASER.TSR_LOPDDR IS 'Indica el lopd derechos';

/** Lopd info adicional **/
ALTER TABLE RSC_TRAPRO ADD TPR_LOPDIA int8;
ALTER TABLE RSC_TRAPRO ADD CONSTRAINT RSC_TPRARC_FK FOREIGN KEY (TPR_LOPDIA) REFERENCES RSC_ARCHIV (ARC_CODI);
COMMENT ON COLUMN RSC_TRAPRO.TPR_LOPDIA IS 'Indica el lopd archivo info adicional';
ALTER TABLE RSC_TRASER ADD TSR_LOPDIA int8;
ALTER TABLE RSC_TRASER ADD CONSTRAINT RSC_TSRARC_FK FOREIGN KEY (TSR_LOPDIA) REFERENCES RSC_ARCHIV (ARC_CODI);
COMMENT ON COLUMN RSC_TRASER.TSR_LOPDIA IS 'Indica el lopd archivo info adicional';


-- Añadimos la traducción del campo URL Externa de un tramite
ALTER TABLE RSC_TRATRA ADD TTR_ULRTRA varchar(256);
COMMENT ON COLUMN RSC_TRATRA.TTR_ULRTRA is 'Indica la url del tramite externo en funcion del idioma';